### ISSUE TITLE
[API de Automação de Consulta] DETRAN / TO / Veículo

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#100]
### Nome da consulta:

DETRAN / TO / Veículo

### URL da consulta:

https://www.to.gov.br/detran/veiculos

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam
- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Consulta cadastro do veículo no Departamento Estadual de Trânsito (DETRAN) de Tocantins (TO).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral e fiscal de veículos, garantindo que os dados do veículo estão atualizados e corretos.
- Pode ser usado por locadoras de veículos para monitorar frotas de veículos.

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://api.infosimples.com/consultas/docs/detran/to/veiculo

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://infosimples.com/consultas/detran-to-veiculo/
