### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / São Paulo / Certidão Tributária Mobiliária

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#101]
### Nome da consulta:

Prefeitura / SP / São Paulo / Certidão Tributária Mobiliária

### URL da consulta:

https://duc.prefeitura.sp.gov.br/certidoes/forms_anonimo/frmConsultaEmissaoCertificado.aspx

### Passo a passo de como realizar manualmente a consulta:

![Prefeitura / SP / São Paulo / Certidão Tributária Mobiliária](https://user-images.githubusercontent.com/274526/129078317-0d129fa3-c0d1-4e8a-8386-c0d4ed3f88cd.png)

### Qual é uma boa descrição desta consulta?

Emite Certidão Tributária de IPTU na Secretaria Municipal da Fazenda da Prefeitura de São Paulo.

**Comment by adrianodennanni** [comment]
@barbolo isso já está desenvolvido?

**Comment by adrianodennanni** [comment]
Disponível em: https://infosimples.com/consultas/pref-sp-sao-paulo-ctm/
