### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MG / NFC-e

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#102]
### Nome da consulta:

SEFAZ / MG / NFC-e

### URL da consulta:

http://nfce.fazenda.mg.gov.br/portalnfce/sistema/consultaarg.xhtml

### Passo a passo de como realizar manualmente a consulta:

![SEFAZ / MG / NFC-e](https://user-images.githubusercontent.com/274526/129079857-f7297e11-eddc-4a23-87ef-dbba4d8ba94d.png)

### Qual é uma boa descrição desta consulta?

Consulta a Nota Fiscal de Consumidor Eletrônica (NFC-e) no governo do estado de Minas Gerais.

**Comment by adrianodennanni** [comment]
Desenvolvimento temporariamente suspenso devido às instabilidades apresentadas no site.

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://api.infosimples.com/consultas/docs/sefaz/mg/nfce-resumida

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://infosimples.com/consultas/sefaz-mg-nfce-resumida/

**Comment by VRossi18** [comment]
Existe uma forma de consultar NFC-e atráves do certificado A1
