### ISSUE TITLE
[API de Automação de Consulta] DETRAN / MS / Gravame

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#104]
### Nome da consulta:

DETRAN / MS / Gravame

### URL da consulta:

https://www2.detran.ms.gov.br/detranet/pserv/veiculo/consGrav/index.asp

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

### Qual é uma boa descrição desta consulta?

Consulta GRAVAME do veículo no Departamento Estadual de Trânsito (DETRAN) de Mato Grosso do Sul (MS).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral e fiscal de veículos, garantindo que os dados informados estão atualizados e corretos.

**Comment by adrianodennanni** [comment]
Necessária para consulta unificada de restrições.

**Comment by rafaelivan** [comment]
O link do site não existe mais.
