### ISSUE TITLE
[API de Automação de Consulta] ECAC / Situação Fiscal do Contribuinte

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#109]
### Nome da consulta:

ECAC / Situação Fiscal do Contribuinte

### URL da consulta:

https://www2.cav.receita.fazenda.gov.br/Servicos/ATSPO/eSitFis.app/GerenciaPedido/PedidoConsultaFiscal.asp?IndNovaConsulta=true&OpConsulta=1

### Parâmetros de entrada necessários para fazer a consulta:

- pkcs12_cert
- pkcs12_pass

### Qual é uma boa descrição desta consulta?

Consulta informações cadastrais e pendências de uma empresa no portal do eCAC (Centro Virtual de Atendimento) da Receita Federal.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão fiscal, garantindo que os dados estão atualizados e corretos.
- Pode ser usada para verificar pendências de uma empresa com a Receita Federal.

**Comment by barbolo** [comment]
API publicada em https://infosimples.com/consultas/ecac-situacao-fiscal/
