### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJBA / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#11]
### Nome da consulta:

Tribunal / TJBA / Processo

### URL da consulta:

http://www2.tjba.jus.br/consultaprocessual/index.wsp

### Parâmetros de entrada necessários para fazer a consulta:

* instancia
* cnj
* numeracao_anterior
* parte
* natureza
* processo
* oab
* parte

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJBA (Tribunal Justiça da Bahia).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
