### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJCE / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#12]
### Nome da consulta:

Tribunal / TJCE / Processo

### URL da consulta:

https://esaj.tjce.jus.br/cpopg/open.do

### Parâmetros de entrada necessários para fazer a consulta:

* processo
* cpf
* rg
* parte
* advogado
* oab
* foro
* carta_precatoria
* documento_delegacia

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJCE (Tribunal de Justiça do Ceará).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
