### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJDF / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#13]
### Nome da consulta:

Tribunal / TJDF / Processo

### URL da consulta:

https://pje.tjdft.jus.br/consultapublica/ConsultaPublica/listView.seam

### Parâmetros de entrada necessários para fazer a consulta:

* processo
* numeracao
* parte
* advogado
* classe
* cpf
* cnpj
* oab

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJDF (Tribunal de Justiça do Distrito Federal).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
