### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Itaúna / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#139]
### Nome da consulta:

Prefeitura / MG / Itaúna / Certidão Negativa de Débitos

### URL da consulta:

https://e-gov.betha.com.br/cdweb/03114-212/contribuinte/rel_cndcontribuinte.faces

### Parâmetros de entrada necessários para fazer a consulta:

- CPF
- CNPJ

### Qual é uma boa descrição desta consulta?

Emite certidão negativa de débitos no portal da Prefeitura do município de Itaúna no estado de Minas Gerais.

**Comment by barbolo** [comment]
API desenvolvida e disponível em https://infosimples.com/consultas/pref-mg-itauna-cnd/
