### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Luz / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#143]
### Nome da consulta:

Prefeitura / MG / Luz / Certidão Negativa de Débitos

### URL da consulta:

https://e-gov.betha.com.br/cdweb/03114-214/contribuinte/rel_cndcontribuinte.faces

### Parâmetros de entrada necessários para fazer a consulta:

- CPF
- CNPJ

### Qual é uma boa descrição desta consulta?

Emite certidão negativa de débitos no portal da Prefeitura do município de Luz no estado de Minas Gerais.

**Comment by barbolo** [comment]
API desenvolvida em https://infosimples.com/consultas/pref-mg-luz-cnd/
