### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Martinho Campos / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#144]
### Nome da consulta:

Prefeitura / MG / Martinho Campos / Certidão Negativa de Débitos

### URL da consulta:

https://isslegal.redemunicipal.com.br/314050601/funcionalidade/certidao-negativa

### Parâmetros de entrada necessários para fazer a consulta:

- CPF
- CNPJ

### Qual é uma boa descrição desta consulta?

Emite certidão negativa de débitos no portal da Prefeitura do município de Martinho Campos no estado de Minas Gerais.

**Comment by barbolo** [comment]
API desenvolvida e disponível em https://infosimples.com/consultas/pref-mg-martinho-campos-cnd/
