### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Araújos / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#146]
### Nome da consulta:

Prefeitura / MG / Araújos / Certidão Negativa de Débitos

### URL da consulta:

http://webcidadao.com.br:8080/web-cidadao-web/pages/certidaodebitos/certidaodebitos.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- CPF
- CNPJ

### Qual é uma boa descrição desta consulta?

Emite certidão negativa de débitos no portal da Prefeitura do município de Araújos no estado de Minas Gerais.

**Comment by barbolo** [comment]
API desenvolvida e disponível em https://infosimples.com/consultas/pref-mg-araujos-cnd/
