### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJGO / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#15]
### Nome da consulta:

Tribunal / TJGO / Processo

### URL da consulta:

https://projudi.tjgo.jus.br/BuscaProcessoPublica?PaginaAtual=4

### Parâmetros de entrada necessários para fazer a consulta:

* processo
* parte
* cpf
* cnpj

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJGO (Tribunal Justiça de Goiás).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
