### ISSUE TITLE
[API de Automação de Consulta] Diário Oficial / SP / Valor Venal de Veículo / IPVA

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#156]
### Nome da consulta:

Diário Oficial / SP / Valor Venal de Veículo / IPVA

### URL da consulta:

https://www.imprensaoficial.com.br/suplementos/fazenda/IPVA2022/index.asp

![Diário Oficial / SP / Valor Venal de Veículo / IPVA](https://user-images.githubusercontent.com/274526/152588511-12afb49a-10ca-49eb-8c06-2e11400c3d91.png)

### Qual é uma boa descrição desta consulta?

Consulta o Valor Venal de um veículo para o cálculo do IPVA de São Paulo.

**Comment by adrianodennanni** [comment]
Consulta disponível em https://infosimples.com/consultas/diario-oficial-sp-valor-venal/
