### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJMG / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#16]
### Nome da consulta:

Tribunal / TJMG / Processo

### URL da consulta:

https://www.tjmg.jus.br/portal-tjmg/processos/andamento-processual/

### Parâmetros de entrada necessários para fazer a consulta:

* instancia
* processo
* parte
* comarca
* oab
* uf

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJMG (Tribunal de Justiça de Minas Gerais).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
