### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJMT / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#17]
### Nome da consulta:

Tribunal / TJMT / Processo

### URL da consulta:

http://servicos.tjmt.jus.br/processos/comarcas/consulta.aspx

### Parâmetros de entrada necessários para fazer a consulta:

* comarcas
* criterio
* parte
* cpf
* cnpj
* numeracao_unica
* codigo_processo
* lotacao
* numero_ano
* data
* advogado
* processos_ano

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJMT (Tribunal de Justiça do Mato Grosso).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
