### ISSUE TITLE
[API de Automação de Consulta] DETRAN / SE / Licenciamento e IPVA

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#188]
### Nome da consulta:

DETRAN / SE / Licenciamento e IPVA

### URL da consulta:

https://www.detran.se.gov.br/portal/?pg=pag_licenc_ficha_parcel

### Parâmetros de entrada necessários para fazer a consulta:

- renavam

### Qual é uma boa descrição desta consulta?

Pode ser usado para gerar guias de pagamento de licenciamento e IPVA para veículos no estado de Sergipe (SE).

### Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usado em gestão fiscal, verificando se existe pendências junto a órgãos públicos.
- Pode ser usada para prevenir fraudes, confirmando se o veículo informado possui débitos.

**Comment by rafaelivan** [comment]
O link do site não existe mais.
