### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJPR / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#20]
### Nome da consulta:

Tribunal / TJPR / Processo

### URL da consulta:

https://pje.tjpr.jus.br/pje/ConsultaPublica/listView.seam

### Parâmetros de entrada necessários para fazer a consulta:

* processo
* parte
* advogado
* classe
* cpf
* cnpj
* oab

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJPR (Tribunal de Justiça do Paraná).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by clinharesadv** [comment]
Ficaria excelente se houvesse a consulta através do maltego!

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
