### ISSUE TITLE
[API de Automação de Consulta] DETRAN / RJ / Nada Consta - Veículo Apreendido

### ISSUE THREAD

**Issue by matheus-s-luiz** [infosimples/infosimples#209]
### Nome da consulta:

DETRAN / RJ / Nada Consta - Veículo Apreendido

### URL da consulta:

https://www.detran.rj.gov.br/_monta_aplicacoes.asp?cod=16&tipo=nadaconsta_veiculo

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- chassi
- renavam
- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Consulta Nada Consta do Veículo Apreendido no Departamento Estadual de Trânsito (DETRAN) do Rio de Janeiro (RJ).

**Comment by adrianodennanni** [comment]
Disponível em: https://infosimples.com/consultas/detran-rj-veiculo-apreendido/
