### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJRJ / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#21]
### Nome da consulta:

Tribunal / TJRJ / Processo

### URL da consulta:

http://www4.tjrj.jus.br/ConsultaUnificada/consulta.do#tabs-numero-indice0

### Parâmetros de entrada necessários para fazer a consulta:

* processo
* origem
* comarca
* competencia
* ano_inicial
* ano_final
* parte
* secao_oab
* oab
* advogado
* cpf
* cnpj
* protocolo
* serventia

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJRJ (Tribunal de Justiça do Rio de Janeiro).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
