### ISSUE TITLE
[API de Automação de Consulta] Receita Federal / PGFN / Lista de Devedores

### ISSUE THREAD

**Issue by matheus-s-luiz** [infosimples/infosimples#210]
### Nome da consulta:

Receita Federal / PGFN / Lista de Devedores

### URL da consulta:

https://www.listadevedores.pgfn.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Pode ser usado para consultar os contribuintes que estão inscritos em dívida ativa da União e do FGTS, na condição de devedor principal, corresponsável ou solidário.

**Comment by adrianodennanni** [comment]
Disponível em: https://infosimples.com/consultas/receita-federal-pgfn-devedores/
