### ISSUE TITLE
[API de Automação de Consulta] TCU / Inabilitados e Inidôneos

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#221]
### Nome da consulta:

TCU / Inabilitados e Inidôneos

### URL da consulta:

https://contas.tcu.gov.br/ords/f?p=INABILITADO:INIDONEOS

### Parâmetros de entrada necessários para fazer a consulta:

- nome
- uf
- numero_processo
- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Consulta pessoas inabilitadas e/ou inidôneas no Tribunal de Contas da União.

**Comment by rafaelivan** [comment]
As APIs foram disponibilizadas:
- https://infosimples.com/consultas/tcu-inabilitados/
- https://infosimples.com/consultas/tcu-inidoneos/
