### ISSUE TITLE
[API de Automação de Consulta] SNCR / Emitir CCIR

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#222]
### Nome da consulta:

SNCR / Emitir CCIR

### URL da consulta:

https://sncr.serpro.gov.br/ccir/emissao

### Parâmetros de entrada necessários para fazer a consulta:

- codigo_imovel
- uf
- municipio
- cpf
- cnpj
- natureza_juridica

### Qual é uma boa descrição desta consulta?

Emite ou consulta a Certidão de Cadastros de Imóveis Rurais (CCIR) no Sistema Nacional de Cadastro Rural (SNCR).

**Comment by Jhstvf4t** [comment]
Sorry boss

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sncr-ccir/
