### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJSC / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#23]
### Nome da consulta:

Tribunal / TJSC / Processo

### URL da consulta:

https://eproc1g.tjsc.jus.br/eproc/externo_controlador.php?acao=processo_consulta_publica

### Parâmetros de entrada necessários para fazer a consulta:

* processo
* chave_processo
* chave_documento
* parte
* oab
* cpf
* cnpj

### Passo a passo de como realizar manualmente a consulta:

1. PASSO_1
2. PASSO_2

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJSC (Tribunal de Justiça de Santa Catarina).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
