### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TST / Banco de Falências

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#231]
### Nome da consulta:

Tribunal / TST / Banco de Falências

### URL da consulta:

https://bancofalencia.tst.jus.br/

### Parâmetros de entrada necessários para fazer a consulta:

- nome
- numero_processo
- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Consulta empresas falidas no Tribunal Superior do Trabalho (TST).

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/tst-banco-falencias/
