### ISSUE TITLE
[API de Automação de Consulta] Receita Federal / MEI / Emissão de Guia de Parcelamento

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#238]
### Nome da consulta:

Receita Federal / MEI / Emissão de Guia de Parcelamento

### URL da consulta:

https://www8.receita.fazenda.gov.br/SimplesNacional/controleAcesso/Autentica.aspx?id=48

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- codigo_acesso

### Passo a passo de como realizar manualmente a consulta:

Parcelamento MEI
1 - Acessar a Aba do Simei Serviços
http://www8.receita.fazenda.gov.br/SimplesNacional/Servicos/Grupo.aspx?grp=t&area=2

2 – Desça a página até as opções de parcelamento e selecione a chave da Opção “Parcelamento – Microempreendedor Individual”

3 – Preencha os campos conforme os dados abaixo:

CNPJ – xxxxxxxxxx
CPF: xxxxxxxxxx
Código de acesso: xxxxxxxxxx
Após preencher, aperte em Continuar.

4 – Acessando o site, aperte novamente em “Simei Serviços / Desça a Pagina até Parcelamento /  e Aperte na chave da Opção “Parcelamento – Microemprendendor Individual”.

5 – Aperte em Emissão de parcela.

6 – Aperte em “Continuar” e depois “Imprimir”

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/receita-federal-simples-mei-eg/
