### ISSUE TITLE
[API de Automação de Consulta] CVM / Processos Administrativos Sancionadores 

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#239]
### Nome da consulta:

CVM / Processos Administrativos Sancionadores 

### URL da consulta:

https://sistemas.cvm.gov.br/asp/cvmwww/inqueritos/formbuscapas.asp

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/cvm-processo-administrativo/
