### ISSUE TITLE
[API de Automação de Consulta] SEMA / MT / APF Rural

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#240]
### Nome da consulta:

SEMA / MT / APF Rural

### URL da consulta:

https://monitoramento.sema.mt.gov.br/apfruralconsulta/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf/cnpj proprietario
- cpf responsável
- apf
- car

### Qual é uma boa descrição desta consulta?

O exercício da atividade de agricultura e pecuária extensiva e semi-extensiva é permitida por meio de Autorização Provisória de Funcionamento de Atividade Rural..

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sema-mt-apf/
