### ISSUE TITLE
[API de Automação de Consulta] MDA / SEAD / Declaração de Aptidão ao PRONAF (DAP)

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#241]
### Nome da consulta:

MDA / SEAD / Declaração de Aptidão ao PRONAF (DAP)

### URL da consulta:

http://smap14.mda.gov.br/extratodap/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

A Declaração de Aptidão ao Programa Nacional de Fortalecimento da Agricultura Familiar (DAP) é o instrumento utilizado para identificar e qualificar as Unidades Familiares de Produção Agrária (UFPA) da agricultura familiar e suas formas associativas organizadas em pessoas jurídicas.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/mda-sead-dap/
