### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MA / DEC / Caixa Postal

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#255]
### Nome da consulta:

SEFAZ / MA / DEC / Caixa Postal

### URL da consulta:

https://sefaznet.sefaz.ma.gov.br/sefaznet/login.do?method=prepareLogin

### Parâmetros de entrada necessários para fazer a consulta:

- pkcs12_cert
- pkcs12_pass
- ignora_nao_lidas

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-ma-dec-caixa-postal/
