### ISSUE TITLE
[API de Automação de Consulta] Receita Federal / SICALC / Gerar DARF

### ISSUE THREAD

**Issue by matheus-s-luiz** [infosimples/infosimples#258]
### Nome da consulta:

Receita Federal / SICALC / Gerar DARF

### URL da consulta:

https://sicalc.receita.economia.gov.br/sicalc/rapido/contribuinte

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf
- data_nascimento
- observacoes
- codigo
- periodo_apuracao
- valor_principal

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/receita-federal-sicalc-darf/
