### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / DF / Certidão de Divida Ativa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#259]
### Nome da consulta:

SEFAZ / DF / Certidão de Divida Ativa

### URL da consulta:

https://ww1.receita.fazenda.df.gov.br/cidadao/certidoes/Certidao

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf

### Qual é uma boa descrição desta consulta?

Emite Certidão de divida ativa na SEFAZ DF.

**Comment by Jhstvf4t** [comment]
I sorry boss

**Comment by Jhstvf4t** [comment]
Please excuse me boss

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-df-certidao-divida-ativa/
