### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / RS / ECAC / CND

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#262]
### Nome da consulta:

SEFAZ / RS / ECAC / CND

### URL da consulta:

https://www.sefaz.rs.gov.br/Receita/PortaleCAC.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- senha

"Escolher a opção Certidões de Situação Fiscal -> Situação Fiscal -Solicitação

Leva 24horas para ficar disponível."

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-rs-ecac-cnd/
