### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / ES / DEC / CND

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#263]
### Nome da consulta:

SEFAZ / ES / DEC / CND

### URL da consulta:

http://app.sefaz.es.gov.br/AgenciaVirtual/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- senha

### Passo a passo de como realizar manualmente a consulta:

1. Clicar na Opção Certidão Tributária
2. Selecionar pessoa e clicar em emitir Certidão.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-es-cnd-login/
