### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PR / DEC / Caixa Postal

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#267]
### Nome da consulta:

SEFAZ / PR / DEC / Caixa Postal

### URL da consulta:

https://receita.pr.gov.br/login

### Parâmetros de entrada necessários para fazer a consulta:

- pkcs12_cert
- pkcs12_pass
- ignora_nao_lidas

**Comment by Jhstvf4t** [comment]
please excuse me boss

**Comment by Jhstvf4t** [comment]
please excuse me because I don't have any more money to go in and out of the workshop

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-pr-dec-caixa-postal/
