### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / ES / DEC / Caixa Postal

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#269]
### Nome da consulta:

SEFAZ / ES / DEC / Caixa Postal

### URL da consulta:

http://app.sefaz.es.gov.br/AgenciaVirtual/

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_senha
- ie

### Passo a passo de como realizar manualmente a consulta:

O sistema irá disponibilizar 7 tipos de caixa postal.
- Cooperação Fiscal
- Auto de infração
- Aviso de Cobrança
- Notificação de Débito
- Dívida Ativa
- Documento Fiscal
- Diversos
A navegação deverá acontecer dentre todas as caixas postais (abas diferentes).

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-es-dec-caixa-postal/
