### ISSUE TITLE
[API de Automação de Consulta] SEMA / PA / Lista de Desmatamento Ilegal do Pará (LDI)

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#270]
### Nome da consulta:

SEMA / PA / Lista de Desmatamento Ilegal do Pará (LDI)

### URL da consulta:

https://monitoramento.semas.pa.gov.br/ldi/

### Parâmetros de entrada necessários para fazer a consulta:

- car

### Passo a passo de como realizar manualmente a consulta:

1. PASSO_1
2. PASSO_2

### Qual é uma boa descrição desta consulta?

A LDI – Lista do Desmatamento Ilegal do Estado do Pará, criada a partir do Decreto Estadual nº 838/2013 que veda a concessão de licenças, autorizações, serviços ou qualquer outro tipo de benefício ou incentivo público por parte dos órgãos e entidades da Administração Pública Estadual aos empreendimentos e atividades situadas em áreas desmatadas ilegalmente no Estado do Pará, a LDI é a ferramenta de consulta oficial do Estado do Pará.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sema-pa-ldi/
