### ISSUE TITLE
[API de Automação de Consulta] Receita Federal / Simples / PGDAS e DEFIS

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#271]
### Nome da consulta:

Receita Federal / Simples / PGDAS e DEFIS

### URL da consulta:

http://www8.receita.fazenda.gov.br/SimplesNacional/Servicos/Grupo.aspx?grp=t&area=1

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf
- codigo_acesso

### Passo a passo de como realizar manualmente a consulta:
https://www.youtube.com/watch?v=TU9SFrOdL5I

### Qual é uma boa descrição desta consulta?

Permite transmitir a declaração mensal, a anual e gerar o DAS

**Comment by rafaelivan** [comment]
Essa API não será disponibilizada neste momento.
