### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Belo Horizonte /  Certidão Negativa de Débitos de IPTU

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#272]
### Nome da consulta:

Prefeitura / MG / Belo Horizonte /  Certidão Negativa de Débitos de IPTU

### URL da consulta:

http://cndonline.siatu.pbh.gov.br/CNDOnline/

### [OPCIONAL] Você gostaria de dizer algo mais que não perguntamos?

Parecido com https://infosimples.com/consultas/pref-mg-belo-horizonte-cnd/, mas acredito que seria necessário fazer algumas adaptações para inserirmos mais parâmetros e pegarmos especificamente a de IPTU.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-mg-belo-horizonte-cndiptu/
