### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Belo Horizonte /  Carnê de IPTU

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#273]
### Nome da consulta:

Prefeitura / MG / Belo Horizonte /  Carnê de IPTU

### URL da consulta:

http://iptuonline.siatu.pbh.gov.br/IptuOnline/index.xhtml

**Comment by rafaelivan** [comment]
O link do site não existe mais.
