### ISSUE TITLE
[API de Automação de Consulta] CNF / Pesquisa de Óbitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#275]
### Nome da consulta:

CNF / Pesquisa de Óbitos

### URL da consulta:

https://falecidosnobrasil.org.br/resultado2.php

### Parâmetros de entrada necessários para fazer a consulta:

- nome
- estado
- cidade

### Qual é uma boa descrição desta consulta?

Pesquisa de Registro de Óbito e Indicação de Cartório

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/cnf-pesquisa-obito/
