### ISSUE TITLE
[API de Automação de Consulta] SESP integração / PR / Situação de Veículos na Polícia Civil

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#277]
### Nome da consulta:

SESP integração / PR / Situação de Veículos na Polícia Civil

### URL da consulta:

https://www.sespintegracao.pr.gov.br/sespintegracao/pages/veiculo/situacao_veiculo.jsf?windowId=93c

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sesp-pr-situacao-veiculo/
