### ISSUE TITLE
[API de Automação de Consulta] Sivisa / SP / Alvará de funcionamento

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#278]
### Nome da consulta:

Sivisa / SP / Alvará de funcionamento

### URL da consulta:

http://sivisa.saude.sp.gov.br/sivisa/cidadao/cidadaoLicenca.consultaEstabelecimento.logic

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- municipio

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sivisa-sp/
