### ISSUE TITLE
[Bug] INCRA / SIGEF / Detalhamento parcelas incompleto

### ISSUE THREAD

**Issue by raphaelsasso** [infosimples/infosimples#279]
https://api.infosimples.com/consultas/docs/incra/sigef/detalhes-parcela
A API só retorna parte dos vértices da área georreferenciada.

Passos para reproduzir o comportamento errado:

1. Quando consulto o código c836c982-b2c6-4445-9f46-8b8e4d02ffb1 na fonte ele me retorna mais de 100 vértices mas quando consulto via a API infosimples o retorno vem apenas essas:

`
"vertices": [
        {
          "codigo": "FWF-P-1625",
          "logitude": "-45°17'27,085\"",
          "sigma_long": "0,00",
          "latitude": "-21°25'34,980\"",
          "sigma_lat": "0,00",
          "altitude": "950,97",
          "sigma_altitude": "0,00",
          "metodo_posicionamento": "PG1"
        },
        {
          "codigo": "FOY-P-10027",
          "logitude": "-45°17'23,780\"",
          "sigma_long": "0,16",
          "latitude": "-21°25'36,100\"",
          "sigma_lat": "0,23",
          "altitude": "949,687",
          "sigma_altitude": "0,21",
          "metodo_posicionamento": "PG6"
        },
        {
          "codigo": "FOY-P-10028",
          "logitude": "-45°17'19,323\"",
          "sigma_long": "0,28",
          "latitude": "-21°25'36,867\"",
          "sigma_lat": "0,31",
          "altitude": "941,354",
          "sigma_altitude": "1,36",
          "metodo_posicionamento": "PG6"
        },
        {
          "codigo": "FOY-P-10029",
          "logitude": "-45°17'18,178\"",
          "sigma_long": "0,26",
          "latitude": "-21°25'37,645\"",
          "sigma_lat": "0,30",
          "altitude": "924,23",
          "sigma_altitude": "0,99",
          "metodo_posicionamento": "PG6"
        },
        {
          "codigo": "FOY-P-10030",
          "logitude": "-45°17'17,337\"",
          "sigma_long": "0,01",
          "latitude": "-21°25'37,151\"",
          "sigma_lat": "0,01",
          "altitude": "925,029",
          "sigma_altitude": "0,03",
          "metodo_posicionamento": "PG6"
        },
        {
          "codigo": "FOY-P-10031",
          "logitude": "-45°17'17,231\"",
          "sigma_long": "0,28",
          "latitude": "-21°25'37,952\"",
          "sigma_lat": "0,27",
          "altitude": "918,855",
          "sigma_altitude": "0,78",
          "metodo_posicionamento": "PG6"
        },
        {
          "codigo": "FOY-P-10032",
          "logitude": "-45°17'18,021\"",
          "sigma_long": "0,29",
          "latitude": "-21°25'38,739\"",
          "sigma_lat": "0,31",
          "altitude": "929,107",
          "sigma_altitude": "1,23",
          "metodo_posicionamento": "PG6"
        },
        {
          "codigo": "FOY-P-10033",
          "logitude": "-45°17'18,428\"",
          "sigma_long": "0,32",
          "latitude": "-21°25'39,055\"",
          "sigma_lat": "0,39",
          "altitude": "922,138",
          "sigma_altitude": "1,25",
          "metodo_posicionamento": "PG6"
        },
        {
          "codigo": "FOY-P-10034",
          "logitude": "-45°17'18,729\"",
          "sigma_long": "0,30",
          "latitude": "-21°25'39,008\"",
          "sigma_lat": "0,40",
          "altitude": "929,363",
          "sigma_altitude": "1,28",
          "metodo_posicionamento": "PG6"
        },
        {
          "codigo": "FOY-P-10035",
          "logitude": "-45°17'18,765\"",
          "sigma_long": "0,26",
          "latitude": "-21°25'39,649\"",
          "sigma_lat": "0,30",
          "altitude": "928,181",
          "sigma_altitude": "0,91",
          "metodo_posicionamento": "PG6"
        }
`

**Comment by barbolo** [comment]
@raphaelsasso obrigado por abrir a issue por aqui também. Nós resolvemos este caso por email, mas também acompanhamos as issues do GitHub.

Fique à vontade para abrir outras issues no futuro se precisar de ajuda.
