### ISSUE TITLE
[API de Automação de Consulta] DETRAN / RS / CNH

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#280]
### Nome da consulta:

DETRAN / RS / CNH

### URL da consulta:

https://www.portaldetransito.rs.gov.br/dtw2/app/servico/hab/consulta-pontuacao-form.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- rg
- cnh
- nome
- data_nascimento

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/detran-rs-cnh/
