### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT /  CONSULTA CREDENCIAMENTOS

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#281]
### Nome da consulta:

SEFAZ / MT /  Consulta Credenciamentos

### URL da consulta:

https://www.sefaz.mt.gov.br/rcr-fe/consultacredenciados

### Parâmetros de entrada necessários para fazer a consulta:

- codigo_beneficio
- razao_social
- nome_beneficio
- ie

### Qual é uma boa descrição desta consulta?

Verifica se a empresa faz parte de um regime de tributação do tipo (ST000001) Regime Optativo de Tributação da Substituição Tributária

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-credenciamentos/
