### ISSUE TITLE
[API de Automação de Consulta] SNCR / Emissão do Certificado de Cadastro do Imóvel Rural (CCIR)

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#284]
### Nome da consulta:

SNCR / Emissão do Certificado de Cadastro do Imóvel Rural (CCIR)

### URL da consulta:

https://sncr.serpro.gov.br/ccir/emissao

### Parâmetros de entrada necessários para fazer a consulta:

- codigo_imovel
- uf_sede
- municipio_sede
- tipo_pessoa
- cpf_titular
- cnpj_titular
- natureza_juridica

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sncr-ccir/
