### ISSUE TITLE
[API de Automação de Consulta] DETRAN / DF / Débitos Veículo

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#287]
### Nome da consulta:

DETRAN / DF / Débitos Veículo

### URL da consulta:

https://portal.detran.df.gov.br/#/servicos/detran-digital/veiculos/consulta/debitos

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

### Qual é uma boa descrição desta consulta?

Consulta débitos do veículo no Departamento Estadual de Trânsito (DETRAN) do Distrito Federal (DF).

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/detran-df-debitos/
