### ISSUE TITLE
[API de Automação de Consulta] Procuradoria Geral do Estado / RJ / Dívida Ativa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#289]
### Nome da consulta:

Procuradoria Geral do Estado / RJ / Dívida Ativa

### URL da consulta:

http://www.consultadividaativa.rj.gov.br/RDGWEBLNX/servlet/StartCISPage?PAGEURL=/cisnatural/NatLogon.html&xciParameters.natsession=Consulta_Debitos_DA

### Parâmetros de entrada necessários para fazer a consulta:

- renavam

**Comment by barbolo** [comment]
API publicada em https://infosimples.com/consultas/pge-rj-divida-ativa/
