### ISSUE TITLE
[API de Automação de Consulta] Seguradora Líder / DPVAT

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#290]
### Nome da consulta:

Seguradora Líder / DPVAT

### URL da consulta:

https://pagamento.dpvatsegurodotransito.com.br/home/PagamentoDpvat?

### Parâmetros de entrada necessários para fazer a consulta:

- renavam
- estado

**Comment by adrianodennanni** [comment]
API publicada no link https://infosimples.com/consultas/dpvat-guia/
