### ISSUE TITLE
[API de Automação de Consulta] DER / PR / CND

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#291]
### Nome da consulta:

DER / PR / CND

### URL da consulta:

https://sider.der.pr.gov.br/cnd/#/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Emite Certidão negativa de débitos junto ao Departamento de Estradas de Rodagem do estado do Paraná

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/der-pr-cnd/
