### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / GO / Produtor Rural

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#292]
### Nome da consulta:

SEFAZ / GO / Produtor Rural

### URL da consulta:

https://www.sefaz.go.gov.br/sintegra/ConsultaCadastroProdutorRural/frmCadastroConsulta_c.htm

### Parâmetros de entrada necessários para fazer a consulta:

- ie

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-go-produtor-rural/
