### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / Goiás / Rio Verde / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#294]
### Nome da consulta:

Prefeitura / Goiás / Rio Verde / Certidão Negativa de Débitos

### URL da consulta:

http://servicos.rioverde.go.gov.br/servicos/certidaonegativa

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-go-rio-verde-cnd/
