### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SC / Imbituba / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#295]
### Nome da consulta:

Prefeitura / SC / Imbituba / Certidão Negativa de Débitos

### URL da consulta:

https://e-gov.betha.com.br/cdweb/03114-270/contribuinte/rel_cndcontribuinte.faces

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sc-imbituba-cnd/
