### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / Goiás / Itumbiara / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#297]
### Nome da consulta:

Prefeitura / Goiás / Itumbiara / Certidão Negativa de Débitos

### URL da consulta:

https://itumbiara.centi.com.br/servicos/certidaonegativa

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-go-itumbiara-cnd/
