### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MT / Rondonópolis  / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#298]
### Nome da consulta:

Prefeitura / MT / Rondonópolis  / Certidão Negativa de Débitos

### URL da consulta:

http://www.rondonopolis.mt.gov.br/tributario_rondonopolis/servlet/portal_serv_servico?12,53

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- tipo_certidao
- finalidade
- observao_finalidade

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/pref-mt-rondonopolis-cnd/
