### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Uberlândia / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#299]
### Nome da consulta:

Prefeitura / MG / Uberlândia / Certidão Negativa de Débitos

### URL da consulta:

http://portalsiat.uberlandia.mg.gov.br/dsf_udi_portal/inicial.do?evento=montaMenu&acronym=CERT_NEG

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_certidao
- inscricao_mobiliaria
- inscricao_reduzida
- inscricao_municipal
- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-mg-uberlandia-cnd/
