### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MA / Balsas / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#300]
### Nome da consulta:

Prefeitura / MA / Balsas / Certidão Negativa de Débitos

### URL da consulta:

http://stm.balsas.d2ti.com.br/credenciamento/jsp/emissaoCertidao/emissaoPublicaCertidao.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_contribuinte
- cpf
- cnpj
- nome
- razao_social
- tipo_certidao
- finalidade_certidao
- inscricao_imobiliaria
- endereco

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-ma-balsas-cnd/
