### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / DF / Certidão Negativa de Débito

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#303]
### Nome da consulta:

SEEC / DF / Certidão Negativa de Débitos

### URL da consulta:

https://ww1.receita.fazenda.df.gov.br/cidadao/certidoes/Certidao

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_emissao
- cpf
- cnpj
- tipo_certidao
- finalidade
- inscricao_imovel
- renavam

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-df-certidao-debitos/
