### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / PA / Itaituba / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#304]
### Nome da consulta:

Prefeitura / PA / Itaituba / Certidão Negativa de Débitos

### URL da consulta:

http://itaituba.tributosmunicipais.net:8110/servicosweb/home.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_emissao
- cadastro_imovel
- cadastro_empresa
- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-pa-itaituba-cnd/
