### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / TO / Colinas / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#305]
### Nome da consulta:

Prefeitura / TO / Colinas / Certidão Negativa de Débitos

### URL da consulta:

https://colinasdotocantins-to.nobesistemas.com.br/tributos/taxpayer_portal_negative_certificates/new

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_certidao
- cpf
- cnpj
- matricula
- inscricao

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-to-colinas-cnd/
