### ISSUE TITLE
[API de Automação de Consulta] ANTT / Embarcador

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#309]
### Nome da consulta:

ANTT / Embarcador

### URL da consulta:

https://appweb1.antt.gov.br/spmi/Site/Login.aspx?ReturnUrl=%2fspmi

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_senha
- cnpj_representado
- tipo_multa

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/antt-sifama-download-auto/
