### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / São Paulo / DSV Digital

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#310]
### Nome da consulta:

Prefeitura / SP / São Paulo / DSV Digital

### URL da consulta:

https://dsvdigital.prefeitura.sp.gov.br/#/login

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_cnpj
- login_senha
- renavam
- placa

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sp-sao-paulo-dsv-digital/
