### ISSUE TITLE
[API de Automação de Consulta] Contas / SABESP / Download de 2ª Via Resumida

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#311]
### Nome da consulta:

Contas / SABESP / Download de 2ª Via Resumida

### URL da consulta:

https://agenciavirtual.sabesp.com.br/minhas-faturas

### Parâmetros de entrada necessários para fazer a consulta:

- rgi

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/contas-sabesp-download-seg-via/
