### ISSUE TITLE
[API de Automação de Consulta] Contas / Comgás / Download de 2ª Via

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#313]
### Nome da consulta:

Contas / Comgás / Download de 2ª Via

### URL da consulta:

https://virtual.comgas.com.br/portal

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- codigo_usuario

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/contas-comgas-download-seg-via/
