### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / AP / Macapá / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#314]
### Nome da consulta:

Prefeitura / AP / Macapá / Certidão Negativa de Débitos

### URL da consulta:

http://macapa.govbr.cloud:8080/cidadao/servlet/br.com.cetil.ar.jvlle.hatendimento

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-ap-macapa-cnd/
