### ISSUE TITLE
[API de Automação de Consulta]  Prefeitura / RJ / Rio de Janeiro / Certidão Tributária de IPTU

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#315]
### Nome da consulta:

 Prefeitura / RJ / Rio de Janeiro / Certidão Tributária de IPTU

### URL da consulta:

http://www2.rio.rj.gov.br/smf/iptucertfiscal/

### Parâmetros de entrada necessários para fazer a consulta:

- inscricao_imobiliaria

### Qual é uma boa descrição desta consulta?

Gera a Certidão de Situação Fiscal e Enfitêutica, documento que concentra as informações relativas ao imóvel para comprovação de regularidade fiscal.

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-rj-rio-janeiro-cert-trib/
