### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Osasco / Certidão Tributária de IPTU

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#316]
### Nome da consulta:

Prefeitura / SP / Osasco / Certidão Tributária de IPTU

### URL da consulta:

http://www.sigt.osasco.sp.gov.br/iTRIB2/ArrSolicitarCnd_Internet.do?acessoExterno=true

### Parâmetros de entrada necessários para fazer a consulta:

- finalidade
- cdc
- cpf_solicitante
- nome
- razao_social
- email
- telefone_contato

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-sp-osasco-iptu/
