### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Jundiaí / Certidão Tributária de IPTU 

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#318]
### Nome da consulta:

Prefeitura / SP / Jundiaí / Certidão Tributária de IPTU 

### URL da consulta:

https://jundiai.sp.gov.br/servicos-online/consulta-de-debito/

### Parâmetros de entrada necessários para fazer a consulta:

- numero_contribuinte
- cnpj_proprietario
- cpf_proprietario

**Comment by barbolo** [comment]
API disponível em https://infosimples.com/consultas/pref-sp-jundiai-cert-trib-iptu/
