### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJGO /  Certidão Nada Consta

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#320]
### Nome da consulta:

Tribunal / TJGO / Certidão Nada Consta

### URL da consulta:

https://www.tjgo.jus.br/index.php/processos/emissao-de-certidoes

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_certidao
- tipo_area
- razao_social
- cnpj
- nome
- cpf
- nome_mae
- data_nascimento
- territorio
- comarca

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/tribunal-tjgo-nada-consta/
