### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJDF / Certidão Nada Consta

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#321]
### Nome da consulta:

Tribunal / TJDF / Certidão Nada Consta

### URL da consulta:

https://cnc.tjdft.jus.br/solicitacao-externa

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- nome
- nome_mae
- nome_pai
- cnpj
- razao_social
- tipo_certidao

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/tribunal-tjdf-nada-consta/
