### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / São Paulo / Dívida Ativa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#322]
### Nome da consulta:

Prefeitura / SP / São Paulo / Dívida Ativa

### URL da consulta:

https://dividaativa.prefeitura.sp.gov.br/ConsultaPagamento/Index?Tela=CONSULTA_DIVIDA

### Parâmetros de entrada necessários para fazer a consulta:

- placa

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sp-sao-paulo-divida-ativa/
