### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / BA / Ilheus / CND

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#323]
### Nome da consulta:

Prefeitura / BA / Ilheus / CND

### URL da consulta:

http://ilheus.metropolisweb.com.br:83/metropolisWEB/tributario/emitirCertidaoDebitoPublico.do?metodo=executarListar

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-ba-ilheus-cnd/
