### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / BA / Juazeiro / CND

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#324]
### Nome da consulta:

Prefeitura / BA / Juazeiro / CND

### URL da consulta:

http://juazeiro.metropolisweb.com.br/metropolisWEB/tributario/emitirCertidaoDebitoPublico.do?metodo=executarListar

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-ba-juazeiro-cnd/
