### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / BA / Vitória da Conquista / CND

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#325]
### Nome da consulta:

SEFAZ / BA / Vitória da Conquista / CND

### URL da consulta:
http://servicos.pmvc.ba.gov.br/certidao_retirada.php

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- inscricao_municipal

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-ba-vit-conq-cnd/
