### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / BA / Camaçari / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#328]
### Nome da consulta:

SEFAZ / BA / Camaçari / Certidão Negativa de Débitos

### URL da consulta:

https://sefazweb.camacari.ba.gov.br/prefeituras/login.tela

### Parâmetros de entrada necessários para fazer a consulta:

- login_usuario
- login_senha

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-ba-camacari-cnd/
