### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RS / Montenegro / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#329]
### Nome da consulta:

Prefeitura / RS / Montenegro / Certidão Negativa de Débitos

### URL da consulta:

https://montenegro.govbr.cloud:10443/cidadao/servlet/br.com.cetil.ar.jvlle.hatendimento

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizaa: https://infosimples.com/consultas/pref-rs-montenegro-cnd/
