### ISSUE TITLE
[API de Imagem] OCR / Nota Fiscal de Serviço / BA / Salvador

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#330]
### Nome da consulta:

OCR / Nota Fiscal de Serviço / BA / Salvador

### Parâmetros de entrada necessários para fazer a consulta:

- image_base64

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/imagens/ocr-nfse-ba-salvador/
