### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Hortolândia / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#335]
### Nome da consulta:

Prefeitura / SP / Hortolândia / Certidão Negativa de Débitos

### URL da consulta:

https://servicos.hortolandia.sp.gov.br/carta-de-servicos/financas/servicos-de-financas/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Passo a passo de como realizar manualmente a consulta:

1. Clicar em "Certidão Negativa de Débitos

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-sp-hortolandia-cnd/
