### ISSUE TITLE
[API de Automação de Consulta] SENATRAN / Meus Veículos

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#337]
### Nome da consulta:

SENATRAN / Meus Veículos

### URL da consulta:

https://portalservicos.senatran.serpro.gov.br/#/veiculos/meus-veiculos

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_senha

### Qual é uma boa descrição desta consulta?

Lista todos os veículos de uma conta do SENATRAN/gov.br

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/senatran-meus-veiculos-posse/
