### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RS / Caxias do Sul / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#338]
### Nome da consulta:

Prefeitura / RS / Caxias do Sul / Certidão Negativa de Débitos

### URL da consulta:

https://grp.caxias.rs.gov.br/grp/tributacao/acessoexterno/certidao/certidao.faces

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by barbolo** [comment]
API desenvolvida: https://infosimples.com/consultas/pref-rs-caxias-do-sul-cnd/
