### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / São Paulo / CONSULTA DÉBITOS DE IPTU

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#339]
### Nome da consulta:

Prefeitura / SP / São Paulo / CONSULTA DÉBITOS DE IPTU

### URL da consulta:

https://duc.prefeitura.sp.gov.br/iptu/consulta_iptu/frm07_SelecaoIPTU.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- cadastro_imovel

### Qual é uma boa descrição desta consulta?

Consulta os dados da Prefeitura de São Paulo e verifica a existência de débitos de IPTU por meio do código de cadastro do imóvel informado.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para verificar se existem dívidas relacionadas ao imóvel

**Comment by rafaelivan** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-sp-sao-paulo-debitos-iptu/
