### ISSUE TITLE
[API de Automação de Consulta] OCR / Contas / Energisa

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#342]
### Nome da consulta:

OCR / Contas / Energisa

### URL da consulta:

COLOQUE_AQUI_A_URL_DA_CONSULTA

### Parâmetros de entrada necessários para fazer a consulta:

- pdf_base64

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/imagens/ocr-contas-energisa/
