### ISSUE TITLE
[API de Automação de Consulta] Conselho Federal de Biomedicina / Cadastro

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#343]
### Nome da consulta:

Conselho Federal de Biomedicina / Cadastro

### URL da consulta:

https://cfbm-br.implanta.net.br/visaonacional/publico/consulta-publica/index

### Parâmetros de entrada necessários para fazer a consulta:

- registro
- nome

### Qual é uma boa descrição desta consulta?

Consulta cadastral de biomédicos no CFBM (Conselho Federal de Biomedicina).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usado em processos de validação cadastral de profissionais cadastrados no CFBM.
- É possível confirmar se o registro de um profissional de biomedicina está ativo.
- É possível verificar a data de registro no Conselho Federal de Biomedicina (CFBM).

**Comment by barbolo** [comment]
API disponível em https://infosimples.com/consultas/cfbm-cadastro/
