### ISSUE TITLE
[API de Automação de Consulta] Conselho Federal de Farmácia / Cadastro

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#344]
### Nome da consulta:

Conselho Federal de Farmácia / Cadastro

### URL da consulta:

https://site.cff.org.br/farmaceutico

### Parâmetros de entrada necessários para fazer a consulta:

- regional
- cidade
- categoria
- registro
- nome

### Qual é uma boa descrição desta consulta?

Consulta cadastral de profissionais inscritos no Conselho Federal de Farmácia (CFF).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usado em processos de validação cadastral de profissionais cadastrados no CFF.
- É possível confirmar se o registro de um profissional de farmácia está ativo.
- É possível verificar a data de registro no Conselho Federal de Farmácia (CFF).

**Comment by barbolo** [comment]
API disponível em https://infosimples.com/consultas/cff-cadastro/
