### ISSUE TITLE
[API de Automação de Consulta] Conselho Regional de Enfermagem / SP / Cadastro

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#345]
### Nome da consulta:

Conselho Regional de Enfermagem / SP / Cadastro

### URL da consulta:

https://servicos.coren-sp.gov.br/consulta-de-profissionais/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- nome
- inscricao

### Qual é uma boa descrição desta consulta?

Consulta cadastral de profissionais no COREN/SP (Conselho Regional de Enfermagem de São Paulo).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usado em processos de validação cadastral de profissionais cadastrados no COREN/SP.
- É possível confirmar se o registro de um profissional de enfermagem está ativo.
- É possível verificar a data de registro no COREN/SP (Conselho Regional de Enfermagem de São Paulo).

**Comment by barbolo** [comment]
API disponível em https://infosimples.com/consultas/coren-sp-cadastro/
