### ISSUE TITLE
[API de Automação de Consulta] SPU / Certidão Enfitêutica

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#347]
### Nome da consulta:

SPU / Certidão Enfitêutica

### URL da consulta:

https://sistema.patrimoniodetodos.gov.br/#/conteudo/22

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf

### Qual é uma boa descrição desta consulta?

Emite a Certidão Negativa de Débitos Patrimoniais do Imóvel e do Responsável, Certidão de Situação de Ocupação/Aforamento e Certidão de Inteiro Teor do Imóvel relativas a imóveis administrados pela Secretaria de Coordenação e Governança do Patrimônio da União - SPU.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para criação de dossiês ou em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Duplicado de #346
