### ISSUE TITLE
[API de Automação de Consulta] SUSEP / Corretores

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#348]
### Nome da consulta:

SUSEP / Corretores

### URL da consulta:

https://www2.susep.gov.br/safe/Corretores/pesquisa

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf

**Comment by barbolo** [comment]
API disponível em https://infosimples.com/consultas/susep-corretores/
