### ISSUE TITLE
[API de Automação de Consulta] DETRAN / BA / Consultar Gravame

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#349]
### Nome da consulta:

DETRAN / BA / Consultar Gravame

### URL da consulta:

https://servicos.detran.ba.gov.br/Gravame/SituacaoGravame

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_senha
- chassi

### Passo a passo de como realizar manualmente a consulta:

1. Acessar o site: https://servicos.detran.ba.gov.br/
2. Entrar com o gov.br ( canto superior direito )
3. No menu selecionar **Veículos** e depois **Serviços Gravame**
4. Clicar em Consultar Gravame
5. Informar o numero do chassi 
6. Clicar em pesquisar

### Qual é uma boa descrição desta consulta?

Verifica o andamento do processo de alienação e desalienação do veículo no site do Detran do estado da Bahia.

**Comment by barbolo** [comment]
API disponível em https://infosimples.com/consultas/detran-ba-gravame/
