### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / AM / NFE/NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#350]
### Nome da consulta:

SEFAZ / AM / NFE/NFC-e

### URL da consulta:

https://sistemas.sefaz.am.gov.br/nfe-consulta/formConsulta.do?tipoConsulta=Completa

### Parâmetros de entrada necessários para fazer a consulta:

- nfe
- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-am-nfce/
