### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / GO / NFE/NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#352]
### Nome da consulta:

SEFAZ / GO / NFE/NFC-e

### URL da consulta:

http://nfe.sefaz.go.gov.br/nfeweb/sites/nfe/consulta-completa

### Parâmetros de entrada necessários para fazer a consulta:

- nfe
- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-go-nfce/
