### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MG / NFE

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#353]
### Nome da consulta:

SEFAZ / MG/ NFE

### URL da consulta:

http://nfe.fazenda.mg.gov.br/portalnfe/sistema/consultaarg.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- nfe

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mg-nfce-resumida/
