### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT / NFE

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#354]
### Nome da consulta:

SEFAZ / MT / NFE

### URL da consulta:

https://www.sefaz.mt.gov.br/nfe/pages/consultanfe/consultarNFe.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- nfe

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-nfce/
