### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MS / NFE

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#355]
### Nome da consulta:

SEFAZ / MS / NFE

### URL da consulta:

 https://www.dfe.ms.gov.br/nfe/consulta/

### Parâmetros de entrada necessários para fazer a consulta:

- nfe

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-ms-nfce/
