### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PE / NFE

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#356]
### Nome da consulta:

SEFAZ / MS / NFE

### URL da consulta:

http://nfe.sefaz.pe.gov.br/nfe-web/entradaConsNfe?tp=C

### Parâmetros de entrada necessários para fazer a consulta:

- nfe

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-pe-nfce/
