### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#358]
### Nome da consulta:

SEFAZ / MT / NFC-e

### URL da consulta:

https://www.sefaz.mt.gov.br/nfce/consultanfce

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-nfce/
