### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MS / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#359]
### Nome da consulta:

SEFAZ / MS / NFC-e

### URL da consulta:

https://www.dfe.ms.gov.br/nfce/consulta/

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-ms-nfce/
