### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PR / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#360]
### Nome da consulta:

SEFAZ / PR / NFC-e

### URL da consulta:

https://sped.fazenda.pr.gov.br/NFCe/webservices/sped/nfce/completa

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-pr-nfce/
