### ISSUE TITLE
[API de Automação de Consulta] DETRAN / BA / Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#362]
### Nome da consulta:

DETRAN / BA / Débitos

### URL da consulta:

https://servicos.detran.ba.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_senha
- renavam

### Passo a passo de como realizar manualmente a consulta:

1. logar no gov.br
2. Menu veículos
3. Opção **“Consultar Licenciamento, Seguro DPVAT...”**
4. Preencher Renavam
5. Buscar PDF **“extrato multas a pagar”** e **“extrato multas em
tramitação”**

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/detran-ba-debitos/
