### ISSUE TITLE
[API de Automação de Consulta] DER / BA / Nada Consta

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#363]
### Nome da consulta:

DER / BA / Nada Consta

### URL da consulta:

http://smt.derba.ba.gov.br:8180/smt/home.action

### Parâmetros de entrada necessários para fazer a consulta:

- renavam
- placa

### Qual é uma boa descrição desta consulta?

Consulta os Autos de Infração em Rodovias Estaduais e Federais delegadas ao DERBA, com o RENAVAM e Placa do veículo.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/der-ba-nada-consta/
