### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / BA / Salvador / Nada consta

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#365]
### Nome da consulta:

Prefeitura / BA / Salvador / Nada consta

### URL da consulta:

http://www.transalvador.salvador.ba.gov.br/conteudo/index.php/multa/nadaConsta

### Parâmetros de entrada necessários para fazer a consulta:

- renavam

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-ba-salvador-nada-consta/
