### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / SP / Cupom Fiscal Eletrônico (SAT)

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#367]
### Nome da consulta:

SEFAZ / SP / Cupom Fiscal Eletrônico (SAT)

### URL da consulta:

https://satsp.fazenda.sp.gov.br/COMSAT/Public/ConsultaPublica/ConsultaPublicaCfe.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- chave

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-sp-cfe/
