### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RN / Touros / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#369]
### Nome da consulta:

Prefeitura / RN / Touros / Certidão Negativa de Débitos

### URL da consulta:

https://www.tinus.com.br/csp/TOUROS/portal/index.csp?868Vjhw2001seswn90236Uosp8567NK=hIRu68vGd575pCu55111dDTyf300VTQrQ9781d0920743Pjjc727

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Emite uma Certidão Negativa de Débitos por meio do CPF/CNPJ informados.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para criação de dossiês ou em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).
- A certidão negativa pode ser usada em processos de licitação, concorrência, cadastro ou homologações diante de fornecedores, bancos, modelos de análise de crédito entre outros.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-rn-touros-cnd/
