### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / PB / Mataraca / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#371]
### Nome da consulta:

Prefeitura / PB / Mataraca / Certidão Negativa de Débitos

### URL da consulta:

https://tributos.elmartecnologia.com.br/portais/mataraca/buscaCertidao.php

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Emite uma Certidão Negativa de Débitos por meio do CPF/CNPJ informados.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para criação de dossiês ou em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).
- A certidão negativa pode ser usada em processos de licitação, concorrência, cadastro ou homologações diante de fornecedores, bancos, modelos de análise de crédito entre outros.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-pb-mataraca-cnd/
