### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Santa Vitória / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#372]
### Nome da consulta:

Prefeitura / MG / Santa Vitória / Certidão Negativa de Débitos

### URL da consulta:

https://sistemas.santavitoria.mg.gov.br/portalcidadao/#075f539f0b7223f116d2c85c4ce1b1752fccb0db1fd92284312b33310fb199ef6050e9373e0f36365cbb7737a0e49e582e657146a648fd13d54aa9e4338df879e807578fb1eeafd7b9e70283f841665c926de53325df44abdbe6fb2ff40fdf8d617449c3e7a3e843f49e3c4d9557cc842c7b0a78b37934a02bb392b40cceb4be

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Emite uma Certidão Negativa de Débitos por meio do CPF/CNPJ informados.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para criação de dossiês ou em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).
- A certidão negativa pode ser usada em processos de licitação, concorrência, cadastro ou homologações diante de fornecedores, bancos, modelos de análise de crédito entre outros.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-mg-santa-vitoria-cnd/
