### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / BA / NFC-e

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#373]
### Nome da consulta:

SEFAZ / BA / NFC-e

### URL da consulta:

http://nfe.sefaz.ba.gov.br/servicos/nfce/Modulos/Geral/NFCEC_consulta_chave_acesso.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-ba-nfce/
