### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / CE / Cupom Fiscal Eletrônico (SAT)

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#374]
### Nome da consulta:

SEFAZ / CE / Cupom Fiscal Eletrônico (SAT)

### URL da consulta:

https://cfe.sefaz.ce.gov.br/mfe/servicos#/cupom-fiscal

### Parâmetros de entrada necessários para fazer a consulta:

- chave

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-ce-cfe/
