### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / RJ / NFC-e Resumida

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#375]
### Nome da consulta:

SEFAZ / RJ / NFC-e Resumida

### URL da consulta:

http://www4.fazenda.rj.gov.br/consultaDFe/paginas/consultaChaveAcesso.faces

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-rj-nfce-resumida/
