### ISSUE TITLE
[API de Automação de Consulta] SUSEP / Empresas

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#376]
### Nome da consulta:

SUSEP / Empresas

### URL da consulta:

https://www2.susep.gov.br/menuatendimento/procura_2011.asp

### Parâmetros de entrada necessários para fazer a consulta:

- razao_social

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/susep-empresas/
