### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / AC / NFC-e Resumida

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#377]
### Nome da consulta:

SEFAZ / AC / NFC-e Resumida

### URL da consulta:

http://sefaznet.ac.gov.br/nfce/consulta.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-ac-nfce/
