### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / AP / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#379]
### Nome da consulta:

 SEFAZ / AP / NFC-e

### URL da consulta:

https://www.sefaz.ap.gov.br/sate/seg/SEGf_AcessarFuncao.jsp?cdFuncao=FIS_1261

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-ap-nfce/
