### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / DF / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#381]
### Nome da consulta:

SEFAZ / DF / NFC-e

### URL da consulta:

https://ww1.receita.fazenda.df.gov.br/documentosfiscais/consultar

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-df-nfce/
