### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / ES / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#382]
### Nome da consulta:

SEFAZ / ES / NFC-e

### URL da consulta:

http://app.sefaz.es.gov.br/ConsultaNFCe/

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-es-nfce/
