### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PA / NFC-e Resumida

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#383]
### Nome da consulta:

SEFAZ / PA / NFC-e Resumida

### URL da consulta:

https://app.sefa.pa.gov.br/consulta-nfce/#/consulta

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-pa-nfce/
