### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PB / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#384]
### Nome da consulta:

SEFAZ / PB / NFC-e

### URL da consulta:

https://www.sefaz.pb.gov.br/servirtual/documentos-fiscais/nfc-e/consultar-nfc-e

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-pb-nfce/
