### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PE / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#385]
### Nome da consulta:

SEFAZ / PE / NFC-e

### URL da consulta:

http://nfce.sefaz.pe.gov.br/nfce/consulta

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-pe-nfce/
