### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PI / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#386]
### Nome da consulta:

SEFAZ / PI / NFC-e

### URL da consulta:

https://www.sefaz.pi.gov.br/nfce/consulta/

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-pi-nfce/
