### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / RN / NFC-e Resumida

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#387]
### Nome da consulta:

SEFAZ / RN / NFC-e Resumida

### URL da consulta:

https://nfce.set.rn.gov.br/portalDFE/NFCe/ConsultaNFCe.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-rn-nfce-resumida/
