### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / SE / NFC-e Resumida

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#390]
### Nome da consulta:

SEFAZ / SE / NFC-e Resumida

### URL da consulta:

http://www.nfce.se.gov.br/portal/portalNoticias.jsp?jsp=barra-menu/servicos/consultaDANFENFCe.htm

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-se-nfce/
