### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / TO / NFC-e

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#391]
### Nome da consulta:

SEFAZ / TO / NFC-e

### URL da consulta:

http://www.sefaz.to.gov.br/nfce/consulta.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-to-nfce/
