### ISSUE TITLE
[API de Automação de Consulta] DETRAN / BA / Veículo

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#392]
### Nome da consulta:

DETRAN / BA / Veículo

### URL da consulta:

https://servicos.detran.ba.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- renavam
- chassi
- Credenciais gov.br

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/detran-ba-veiculo/
