### ISSUE TITLE
[API de Automação de Consulta] SEGURADORA / DEKRA / Laudos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#393]
### Nome da consulta:

SEGURADORA / DEKRA / Laudos

### URL da consulta:

https://agendamento.dekra.com.br/login?ReturnUrl=%2F

### Parâmetros de entrada necessários para fazer a consulta:

- login
- senha
- placa

### Passo a passo de como realizar manualmente a consulta:

1. Consulta Laudo ECV/LCD

**Comment by rafaelivan** [comment]
As APIs foram disponibilizadas:
- https://infosimples.com/consultas/laudos-veiculares-dekra-lcd/
- https://infosimples.com/consultas/laudos-veiculares-dekra-ecv/
