### ISSUE TITLE
[API de Automação de Consulta] PLENAVER / ECV / LAUDOS

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#394]
### Nome da consulta:

PLENAVER / ECV / LAUDOS

### URL da consulta:

https://www.plenaver.com.br/login

### Parâmetros de entrada necessários para fazer a consulta:

- login
- senha
- placa

### Passo a passo de como realizar manualmente a consulta:

1. Vistoria
2. Consultar Laudo
3. Inserir a placa
4. Selecionar cliente
5. Localizar
6. Pegar sempre o laudo mais atualizado, conforme coluna Data.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/laudos-veiculares-plenaver-ecv/
