### ISSUE TITLE
[API de Automação de Consulta] PLENAVER / LCD / LAUDOS

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#395]
### Nome da consulta:

PLENAVER / LCD / LAUDOS

### URL da consulta:

https://www.plenaver.com.br/login

### Parâmetros de entrada necessários para fazer a consulta:

- login
- senha
- placa

### Passo a passo de como realizar manualmente a consulta:

1. Vistoria LCD/PMG
2. Consulta de laudos
3. Inserir a placa
4. PDF do laudo PMG

**Comment by rafaelivan** [comment]
A API está disponibilizada: https://infosimples.com/consultas/laudos-veiculares-plenaver-lcd/
