### ISSUE TITLE
[API de Automação de Consulta] SEGURADORA / TOKIO / Laudos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#396]
### Nome da consulta:

SEGURADORA / TOKIO / Laudos

### URL da consulta:

https://ssoportais3.tokiomarine.com.br/openam/XUI/?realm=TOKIOLFR&goto=http://portalparceiros.tokiomarine.com.br/?_gl=1*16ijgty*_ga*NzQzMTYwMzA2LjE2ODAwODYxMzM.*_ga_M3GQZ9PQWS*MTY4MDA4NjEzMy4xLjAuMTY4MDA4NjE3My4yMC4wLjA.&_ga=2.135762289.1594648712.1680086133-743160306.1680086133#login/

### Parâmetros de entrada necessários para fazer a consulta:

- login_usuario
- login_senha
- placa

**Comment by rafaelivan** [comment]
As APIs estão disponibilizadas:
- https://infosimples.com/consultas/laudos-veiculares-tokio-ecv/
- https://infosimples.com/consultas/laudos-veiculares-tokio-lcd/
