### ISSUE TITLE
[API de Automação de Consulta] TCU / Certidão Negativa de Processo

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#397]
### Nome da consulta:

TCU / Certidão Negativa de Processo

### URL da consulta:

https://contas.tcu.gov.br/certidao/Web/Certidao/NadaConsta/home.faces

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/tcu-cnp/
