### ISSUE TITLE
[API de Automação de Consulta] BCB / Valores a Receber

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#398]
### Nome da consulta:

BCB / Valores a Receber

### URL da consulta:

https://valoresareceber.bcb.gov.br/publico

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- data_nascimento
- cnpj
- data_abertura_empresa

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/bcb-valores-receber/
