### ISSUE TITLE
[API de Automação de Consulta] Junta Comercial / SP / NIRE a partir de Sócio

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#4]
### Nome da consulta:

Junta Comercial / SP / NIRE a partir de Sócio

### URL da consulta:

https://www.jucesponline.sp.gov.br/BuscaAvancada.aspx?IDProduto=

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- senha
- socio_nome 
- socio_cpf
- socio_cnpj

### Passo a passo de como realizar manualmente a consulta:

1. Com `cpf` e `senha`, faz login na JUCSP
2. Com os filtros `nome_socio`, `cpf_socio` ou `cnpj_socio` faz pesquisas avançada de empresas
3. Retorna os 15 primeiros resultados identificados. Cada resultado tem os campos: `nire`, `nome`, `municipio`, `socio_nome`, `socio_documento`

### Qual é uma boa descrição desta consulta?

Localiza o Número de identificação do Registro de Empresas (NIRE) na Junta Comercial do Estado de São Paulo (JUCESP) a partir do nome ou do documento (CPF/CNPJ) do sócio da empresa. A API retornará até 15 resultados da pesquisa.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral e fiscal de pessoas jurídicas, garantindo que dados informados estão atualizados e corretos.
- Pode ser usada para rastreamento de ativos.

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://api.infosimples.com/consultas/docs/junta-comercial/sp/nire-socio

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://infosimples.com/consultas/junta-comercial-sp-nire-socio/
