### ISSUE TITLE
[API de Automação de Consulta] SENATRAN / Meus Veículos (Detalhes)

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#400]
### Nome da consulta:

SENATRAN / Meus Veículos (Detalhes)

### URL da consulta:

https://portalservicos.senatran.serpro.gov.br/#/veiculos/meus-veiculos

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam
- login_govbr

### Qual é uma boa descrição desta consulta?

Retorna detalhes do veículo na posse de um usuário do SENATRAN/gov.br através da placa e renavam.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral, garantindo que os dados do veículo estão atualizados e corretos.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/senatran-meus-veiculos-posse/
