### ISSUE TITLE
[API de Automação de Consulta] B3 / Participantes

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#401]
### Nome da consulta:

B3 / Participantes

### URL da consulta:

https://www.b3.com.br/pt_br/produtos-e-servicos/participantes/busca-de-participantes/participantes/

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/b3-participantes/
