### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TRF6 / Certidão Negativa Cível e Criminal

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#402]
### Nome da consulta:

Tribunal / TRF6 / Certidão Negativa Cível e Criminal

### URL da consulta:

https://sistemas.trf6.jus.br/certidao/#/solicitacao

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_certidao
- orgao
- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/tribunal-trf6-certidao/
