### ISSUE TITLE
[API de Automação de Consulta] Contas / CPFL / Download (Empresas)

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#403]
### Nome da consulta:

Contas / CPFL / Download (Empresas)

### URL da consulta:

https://www.cpfl.com.br/empresas

### Parâmetros de entrada necessários para fazer a consulta:

- login_email
- login_senha
- instalcao

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/contas-cpfl-download-empresas/
