### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RJ / Rio de Janeiro / Certidão de Elementos Cadastrais - IPTU

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#404]
### Nome da consulta:

Prefeitura / RJ / Rio de Janeiro / Certidão de Elementos Cadastrais - IPTU

### URL da consulta:

http://www2.rio.rj.gov.br/smf/iptucertcadastral/default.asp

### Parâmetros de entrada necessários para fazer a consulta:

- inscricao_imobiliaria

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-rj-rio-janeiro-cert-cad/
