### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJMG / Processos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#406]
### Nome da consulta:

Tribunal / TJMG / Processos

### URL da consulta:

https://pje-consulta-publica.tjmg.jus.br/

### Parâmetros de entrada necessários para fazer a consulta:

- numero_processo
- nome_parte
- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/tribunal-tjmg-processo/
