### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RS / Porto Alegre / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#410]
### Nome da consulta:

Prefeitura / RS / Porto Alegre / Certidão Negativa de Débitos

### URL da consulta:

https://siat.procempa.com.br/siat/ArrSolicitarCertidaoGeralDebTributarios_Internet.do

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-rs-porto-alegre-cnd/
