### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SC / Florianópolis / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#411]
### Nome da consulta:

Prefeitura / SC / Florianópolis / Certidão Negativa de Débitos

### URL da consulta:

https://e-gov.betha.com.br/cdweb/03114-344/contribuinte/directlogin.faces?iEntidades=90ZzetX_DLs=&iDatabases=Y_c_RzY_6Uc=

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sc-florianopolis-cnd/
