### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / PE / Recife / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#412]
### Nome da consulta:

Prefeitura / PE / Recife / Certidão Negativa de Débitos

### URL da consulta:

https://recifeemdia.recife.pe.gov.br/emissaoCertidao/4

### Parâmetros de entrada necessários para fazer a consulta:

- inscricao
- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-pe-recife-cnd/
