### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RS / Três Coroas / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#414]
### Nome da consulta:

Prefeitura / RS / Três Coroas / Certidão Negativa de Débitos

### URL da consulta:

http://cidadao.trescoroas.rs.gov.br:8080/cidadao/servlet/br.com.cetil.ar.jvlle.hcertidao

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-rs-tres-coroas-cnd/
