### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MA / São Luís / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#415]
### Nome da consulta:

Prefeitura / MA / São Luís / Certidão Negativa de Débitos

### URL da consulta:

https://stm.semfaz.saoluis.ma.gov.br/credenciamento/jsp/emissaoCertidao/emissaoPublicaCertidao.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-ma-sao-luis-cnd/
