### ISSUE TITLE
[API de Automação de Consulta] DETRAN / PR / Resumo

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#419]
### Nome da consulta:

DETRAN / PR / Resumo

### URL da consulta:

https://www.extratodebito.detran.pr.gov.br/detranextratos/geraExtrato.do?action=iniciarProcesso

### Parâmetros de entrada necessários para fazer a consulta:

- renavam

**Comment by rafaelivan** [comment]
As consultas foram disponibilizadas:
- https://infosimples.com/consultas/detran-pr-veiculo/
- https://infosimples.com/consultas/detran-pr-veiculo-completa/
