### ISSUE TITLE
[API de Automação de Consulta] DETRAN / PR / Emissão Licenciamento

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#420]
### Nome da consulta:

DETRAN / PR / Emissão Licenciamento

### URL da consulta:

https://www.extratodebito.detran.pr.gov.br/detranextratos/geraExtrato.do?action=iniciarProcesso

### Parâmetros de entrada necessários para fazer a consulta:

- renavam

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/detran-pr-licenciamento/
