### ISSUE TITLE
[API de Automação de Consulta] Capacidade de Pagamento (CAPAG)

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#421]
### Nome da consulta:

Capacidade de Pagamento (CAPAG)

### URL da consulta:

https://www.tesourotransparente.gov.br//temas/estados-e-municipios/capacidade-de-pagamento-capag

### Parâmetros de entrada necessários para fazer a consulta:

- uf
- municipio

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/tesouro-nacional-capag/
