### ISSUE TITLE
[API de Automação de Consulta] Portal da Transparência / Repasse de Verba

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#422]
### Nome da consulta:

Portal da Transparência / Repasse de Verba

### URL da consulta:

https://portaldatransparencia.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- consultado
- ano

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/portal-transparencia-repasse/
