### ISSUE TITLE
[API de Automação de Consulta] SICONFI / Declaração Fiscal

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#423]
### Nome da consulta:

SICONFI / Declaração Fiscal

### URL da consulta:

https://siconfi.tesouro.gov.br/siconfi/pages/public/declaracao/declaracao_list.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- esfera
- ente
- poder
- orgao
- exercicio

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/siconfi-declaracao/
