### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / GO / Goiânia / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#424]
### Nome da consulta:

Prefeitura / GO / Goiânia / Certidão Negativa de Débitos

### URL da consulta:

https://www.goiania.go.gov.br/sistemas/sccer/asp/sccer00300f0.asp

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-go-goiania-cnd/
