### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / GO / Aparecida de Goiânia / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#425]
### Nome da consulta:

Prefeitura / GO / Aparecida de Goiânia / Certidão Negativa de Débitos

### URL da consulta:

https://sigp.aparecida.go.gov.br/sig/app.html#/servicosonline/debito-contribuinte

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-go-aparecida-goiania-cnd/
