### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Mairiporã / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#426]
### Nome da consulta:

Prefeitura / SP / Mairiporã / Certidão Negativa de Débitos

### URL da consulta:

https://portal.cidadao.conam.com.br/mairipora/certidao_mobiliario.php

### Parâmetros de entrada necessários para fazer a consulta:

- inscricao

**Comment by rafaelivan** [comment]
A API disponibilizada: https://infosimples.com/consultas/pref-sp-mairipora-cnd/
