### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Campinas / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#428]
### Nome da consulta:

Prefeitura / SP / Campinas / Certidão Negativa de Débitos

### URL da consulta:

https://certidaoqualquerorigem.campinas.sp.gov.br/processos

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sp-campinas-cnd/
