### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Contagem / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#429]
### Nome da consulta:

Prefeitura / MG / Contagem / Certidão Negativa de Débitos

### URL da consulta:

http://receita.contagem.mg.gov.br/certidaonegativa/emissao/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-mg-contagem-cnd/
