### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RS / Santa Cruz do Sul / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#430]
### Nome da consulta:

Prefeitura / RS / Santa Cruz do Sul / Certidão Negativa de Débitos

### URL da consulta:

https://grp.santacruz.rs.gov.br/grp/acessoexterno/programaAcessoExterno.faces?codigo=684670

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-rs-santa-cruz-do-sul-cnd/
