### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MT / Cuiabá / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#431]
### Nome da consulta:

Prefeitura / MT / Cuiabá / Certidão Negativa de Débitos

### URL da consulta:

https://portalfazenda.cuiaba.mt.gov.br/portalfazenda/PortalContribuinte/EmitirCertidao

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-mt-cuiaba-cnd/
