### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / AL / Arapiraca / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#433]
### Nome da consulta:

Prefeitura / AL / Arapiraca / Certidão Negativa de Débitos

### URL da consulta:

https://arapiraca.abaco.com.br/eagata/servlet/hwloginusuario?20=

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
O link do site não existe mais.
