### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / PR / Curitiba / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#434]
### Nome da consulta:

Prefeitura / PR / Curitiba / Certidão Negativa de Débitos

### URL da consulta:

https://cnd-cidadao.curitiba.pr.gov.br/Certidao/SolicitarCnpj

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-pr-curitiba-cnd/
