### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / PR / Ampére / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#435]
### Nome da consulta:

Prefeitura / PR / Ampére / Certidão Negativa de Débitos

### URL da consulta:

http://nfse1.publica.inf.br/ampere_sefaz/jsp/cnd/index.jsp

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-pr-ampere-cnd/
