### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / PR / Francisco Beltrão / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#436]
### Nome da consulta:

Prefeitura / PR / Francisco Beltrão / Certidão Negativa de Débitos

### URL da consulta:

http://pmfb.franciscobeltrao.com.br:7474/esportal/stmcertidao.load.logic

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-pr-francisco-beltrao-cnd/
