### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MS / Campo Grande / NFS-e (Nota Fiscal Eletrônica de Serviços)

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#438]
### Nome da consulta:

Prefeitura / MS / Campo Grande / NFS-e (Nota Fiscal Eletrônica de Serviços)

### URL da consulta:

https://nfse.pmcg.ms.gov.br/NotaFiscal/verificarAutenticidade.php

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj_prestador
- numero_nota
- inscricao_municipal
- codigo_verificacao

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-ms-campo-grande-nfs/
