### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MT / Cuiabá / NFS-e (Nota FIscal Eletrônica de Serviços)

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#440]
### Nome da consulta:

Prefeitura / MT / Cuiabá / NFS-e (Nota FIscal Eletrônica de Serviços)

### URL da consulta:

https://onlinecba.issnetonline.com.br/cuiaba/NotaDigital/VerificaAutenticidade.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- inscricao_municipal
- serie_nota
- numero_nota
- chave_identificacao

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-mt-cuiaba-nfs/
