### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / São Bernardo do Campo / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#441]
### Nome da consulta:

Prefeitura / SP / São Bernardo do Campo / Certidão Negativa de Débitos

### URL da consulta:

https://www.saobernardo.sp.gov.br/web/sbc/negativa-de-debitos

### Parâmetros de entrada necessários para fazer a consulta:

- requerente_cpf
- requerente_nome
- requerente_email
- requerente_telefone
- cpf
- cnpj
- inscricao

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sp-sao-bernardo-cnd/
