### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / AC / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#442]
### Nome da consulta:
SEFAZ / AC / NFC-e Completa

### URL da consulta:
http://sefaznet.ac.gov.br/nfce/consulta.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-ac-nfce/
