### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / AM / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#443]
### Nome da consulta:
SEFAZ / AM / NFC-e Completa

### URL da consulta:
https://sistemas.sefaz.am.gov.br/nfceweb/consultarNFCe.do?acao=abrirAbas

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-am-nfce-completa/
