### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / BA / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#444]
### Nome da consulta:

SEFAZ / BA / NFC-e Completa

### URL da consulta:

http://nfe.sefaz.ba.gov.br/servicos/nfce/Modulos/Geral/NFCEC_consulta_abas.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-ba-nfce-completa/
