### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / ES / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#445]
### Nome da consulta:

SEFAZ / ES / NFC-e Completa

### URL da consulta:

http://app.sefaz.es.gov.br/ConsultaNFCe/ConsultaAbas.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-es-nfce/
