### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / GO / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#446]
### Nome da consulta:

SEFAZ / GO / NFC-e Completa

### URL da consulta:

http://nfe.sefaz.go.gov.br/nfeweb/sites/nfce/render/NFCe

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-go-nfce/
