### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MA / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#447]
### Nome da consulta:

SEFAZ / MA / NFC-e Completa

### URL da consulta:

http://www.nfce.sefaz.ma.gov.br/portal/pages/consultaNFCeDetalhe.xhtml?dswid=-4390

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-ma-nfce/
