### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MG / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#448]
### Nome da consulta:

SEFAZ / MG / NFC-e Completa

### URL da consulta:

http://nfce.fazenda.mg.gov.br/portalnfce/sistema/consultaresumida.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mg-nfce-resumida/
