### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PE / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#449]
### Nome da consulta:

SEFAZ / PE / NFC-e Completa

### URL da consulta:

http://nfce.sefaz.pe.gov.br/nfce-web/entradaConsNfce?tp=C

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-pe-nfce/
