### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PI / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#450]
### Nome da consulta:

SEFAZ / PI / NFC-e Completa

### URL da consulta:

https://www.sefaz.pi.gov.br/nfce/views/resultadoConsulta.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-pi-nfce/
