### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / RN / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#451]
### Nome da consulta:

SEFAZ / RN / NFC-e Completa

### URL da consulta:

https://nfce.set.rn.gov.br/portalDFE/NFCe/DadosNFCe.aspx?tipoConsulta=completo

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-rn-nfce-resumida/
