### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / SE / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#452]
### Nome da consulta:

SEFAZ / SE / NFC-e Completa

### URL da consulta:

http://www.nfce.se.gov.br/portal/consultaXSLT/index.jsp

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-se-nfce/
