### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / TO / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#453]
### Nome da consulta:

SEFAZ / TO / NFC-e Completa

### URL da consulta:

http://www.sefaz.to.gov.br/nfce/nFCe400.jsf#

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-se-nfce/

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-to-nfce/
