### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / CE / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#454]
### Nome da consulta:

SEFAZ / CE / NFC-e Completa

### URL da consulta:

http://nfe.sefaz.ce.gov.br/pages/consultaNfeXSLTCompleta.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-ce-nfce/
