### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / RJ / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#455]
### Nome da consulta:

SEFAZ / RJ / NFC-e Completa

### URL da consulta:

http://www4.fazenda.rj.gov.br/consultaDFe/paginas/resultadoDfeDetalhado.faces?cid=2

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-rj-nfce-completa/
