### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Valor Venal de Referência

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#458]
### Nome da consulta:

Prefeitura / SP / Valor Venal de Referência

### URL da consulta:

https://itbi.prefeitura.sp.gov.br/valorreferencia/tvm/frm_tvm_consulta_valor.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- sql
- data

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sp-sao-paulo-valor-ref/
