### ISSUE TITLE
[API de Automação de Consulta] DETRAN / RS / Guia de Pagamento de Multas

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#459]
### Nome da consulta:

DETRAN / RS / Guia de Pagamento

### URL da consulta:

https://www.portaldetransito.rs.gov.br/dtw2/app/servico/ifr/guia-pagamento-multas.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/detran-rs-guia-pagamento/
