### ISSUE TITLE
[API de Automação de Consulta] ANP / Revendas

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#460]
### Nome da consulta:

ANP / Revendas

### URL da consulta:

https://cpl.anp.gov.br/anp-cpl-web/public/simp/consulta-revendas/consulta.xhtml?dswid=2379

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/anp-revendas/
