### ISSUE TITLE
[API de Automação de Consulta] INCRA / Disponibilizador de Coordenadas

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#461]
### Nome da consulta:

INCRA / Disponibilizador de Coordenadas

### URL da consulta:

https://acervofundiario.incra.gov.br/Conversao01/faces/index.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- numero_certificacao

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/incra-coordenadas/
