### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Araçariguama / NFS-e (Nota Fiscal Eletrônica de Serviços)

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#462]
### Nome da consulta:

Prefeitura / SP / Araçariguama / NFS-e (Nota Fiscal Eletrônica de Serviços)

### URL da consulta:

http://portal.aracariguama.sp.gov.br/CECAM.ISSWEB/asp/wfValidaNFE.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj_prestador
- numero_nota
- codigo_verificacao

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sp-aracariguama-nfs/
