### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Jaguariúna / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#463]
### Nome da consulta:

Prefeitura / SP / Jaguariúna / Certidão Negativa de Débitos

### URL da consulta:

[https://municipio.jaguariuna.sp.gov.br/busca.html](https://municipio.jaguariuna.sp.gov.br/busca.html)

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_certidao
- cpf
- cnpj

**Comment by rafaelivan** [comment]
O link do site não existe mais.
