### ISSUE TITLE
[API de Automação de Consulta] Receita Federal / NFS-e (Nota Fiscal Eletrônica de Serviços)

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#465]
### Nome da consulta:

Receita Federal / NFS-e (Nota Fiscal Eletrônica de Serviços)

### URL da consulta:

https://www.nfse.gov.br/consultapublica

### Parâmetros de entrada necessários para fazer a consulta:

- chave

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/receita-federal-nfse/
