### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TRT2 / Certidão Eletrônica de Ações Trabalhistas (CEAT) - Processos Eletrônicos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#466]
### Nome da consulta:

Tribunal / TRT2 / Certidão Eletrônica de Ações Trabalhistas (CEAT) - Processos Eletrônicos

### URL da consulta:

https://pje.trt2.jus.br/certidoes/trabalhista/emissao

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf
- nome_completo

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/tribunal-trt2-ceat-digital/
