### ISSUE TITLE
[API de Automação de Consulta] DETRAN / PR / Pontuação CNH

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#467]
### Nome da consulta:

DETRAN / PR / Pontuação CNH

### URL da consulta:

https://www.extratodebito.detran.pr.gov.br/detranextratos/gerarExtratoPontuacao.do?action=viewExtract

### Parâmetros de entrada necessários para fazer a consulta:

- registro_cnh
- modelo
- cpf
- validade_cnh

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/detran-pr-cnh/
