### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / SP / Cadin Estadual

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#468]
### Nome da consulta:

SEFAZ / SP / Cadin Estadual

### URL da consulta:

https://www.fazenda.sp.gov.br/cadin_estadual/pages/publ/cadin.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-sp-cadin/
