### ISSUE TITLE
[API de Automação de Consulta] GIT Cidadão (PR) / Notificações

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#469]
### Nome da consulta:

GIT Cidadão (PR) / Notificações

### URL da consulta:

https://www.gitcidadao.pr.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- renavam
- placa
- nome_infrator
- cpf_infrator
- rg_infrator
- uf_rg
- numero_celula
- numero_registro
- uf_cnh
- telefone_infrator
- email_infrator

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/git-cidadao-pr-notificacoes/
