### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / GO / Anápolis / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#470]
### Nome da consulta:

Prefeitura / GO / Anápolis / Certidão Negativa de Débitos

### URL da consulta:

http://www.consultas.anapolis.go.gov.br/ansprocesso/certidaocadeconomico/economico.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-go-anapolis-cnd/
