### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / GO / Morrinhos / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#471]
### Nome da consulta:

Prefeitura / GO / Morrinhos / Certidão Negativa de Débitos

### URL da consulta:

https://morrinhos.prodataweb.inf.br/sig/app.html#/servicosonline/debito-contribuinte

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-go-morrinhos-cnd/
