### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SC / Itajaí / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#477]
### Nome da consulta:

Prefeitura / SC / Itajaí / Certidão Negativa de Débitos

### URL da consulta:

https://iss.itajai.sc.gov.br/sefaz/jsp/cnd/index.jsp

### Parâmetros de entrada necessários para fazer a consulta:

- finalidade
- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-sc-itajai-cnd/
