### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / São Paulo / Certidão de Dados Cadastrais do Imóvel

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#479]
### Nome da consulta:

Prefeitura / SP / São Paulo / Certidão de Dados Cadastrais do Imóvel

### URL da consulta:

http://notcertiptu.prefeitura.sp.gov.br/PaginasRestritas/frm003_Gerar_Cert_Dados_Cad.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_cnpj
- login_senha
- cadastro_imovel
- ano_exercicio

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-sp-sao-paulo-dados-imovel/
