### ISSUE TITLE
[API de Automação de Consulta] INMETRO / Instrumentos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#480]
### Nome da consulta:

INMETRO / Instrumentos

### URL da consulta:

https://servicos.rbmlq.gov.br/instrumento

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_instrumento
- placa
- numero_inmetro
- numero_serie

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/inmetro-instrumentos-vc-tanque/
