### ISSUE TITLE
[API de Automação de Consulta] DETRAN / MS / Guia Flex

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#481]
### Nome da consulta:

DETRAN / MS / Guia Flex

### URL da consulta:

https://www.meudetran.ms.gov.br/veiculo.php

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

**Comment by rafaelivan** [comment]
As APIs foram disponibilizadas:
https://infosimples.com/consultas/detran-ms-licenciamentos-flex/
https://infosimples.com/consultas/detran-ms-multas-flex/
