### ISSUE TITLE
[API de Automação de Consulta] DETRAN / GO / Veículo

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#482]
### Nome da consulta:

DETRAN / GO / Veículo

### URL da consulta:

https://www.go.gov.br/servicos-digitais/detran/consulta-veiculos/consultar-dados

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_senha

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/detran-go-veiculo/
