### ISSUE TITLE
[API de Automação de Consulta] Contas / Enel / CE / Download

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#484]
### Nome da consulta:

Contas / Enel / CE / Download

### URL da consulta:

https://www.enel.com.br/pt-ceara/login.html

### Parâmetros de entrada necessários para fazer a consulta:

- login_email
- login_senha
- instalacao

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/contas-enel-ce-download/
