### ISSUE TITLE
[API de Automação de Consulta] OCR / Contas / Enel (Ceará)

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#485]
### Nome da consulta:

OCR / Contas / Enel (Ceará)

### Parâmetros de entrada necessários para fazer a consulta:

- pdf_base64

### Observações:

Adicionar o parse do OCR na classe existente para contas Enel `Images::Ocr::Contas::Enel`

**Comment by rafaelivan** [comment]
O OCR foi disponibilizado: https://infosimples.com/imagens/ocr-contas-enel/
