### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / CE / Fortaleza / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#486]
### Nome da consulta:

Prefeitura / CE / Fortaleza / Certidão Negativa de Débitos

### URL da consulta:

https://grpfor.sefin.fortaleza.ce.gov.br/grpfor/pagesPublic/certidoes/emitirCertidao.seam

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-ce-fortaleza-cnd/
