### ISSUE TITLE
[API de Automação de Consulta] Prefetura / SP / São Paulo / Regularidade OTTC

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#487]
### Nome da consulta:

Prefetura / SP / São Paulo / Regularidade OTTC

### URL da consulta:

https://web1.sf.prefeitura.sp.gov.br/NMT/Publico/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- placa

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sp-sao-paulo-ottc/
