### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Campinas / Regularidade OTTC

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#488]
### Nome da consulta:

Prefeitura / SP / Campinas / Regularidade OTTC

### URL da consulta:

http://www.emdec.com.br/eficiente/sites/portalemdec/pt-br/site.php?secao=transporteaplicativo&pub=14965

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- placa
- nome_completo

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-sp-campinas-ottc/
