### ISSUE TITLE
[API de Automação de Consulta] Sefaz / MT / Reimpressão de CND

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#489]
### Nome da consulta:

Sefaz / MT / Reimpressão de CND

### URL da consulta:

https://www.sefaz.mt.gov.br/cnd/certidao/servlet/ServletRotd?origem=57

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- ie

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-reimpressao-cnd/
