### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT / Reimpressão de Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#492]
### Nome da consulta:

SEFAZ / MT / Reimpressão de Certidão Negativa de Débitos

### URL da consulta:

https://www.sefaz.mt.gov.br/cnd/certidao/servlet/ServletRotd?origem=57

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-reimpressao-cnd/
