### ISSUE TITLE
[API de Automação de Consulta] Junta Comercial / SP / NIRE pelo mapa

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#5]
### Nome da consulta:

Junta Comercial / SP / NIRE pelo mapa

### URL da consulta:

https://www.jucesponline.sp.gov.br/Mapas.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- razao_social
- objeto
- logradouro
- cep
- bairro
- municipio
- uf

### Passo a passo de como realizar manualmente a consulta:

1. Entrar na página https://www.jucesponline.sp.gov.br/Mapas.aspx
2. Preencher filtros de busca usando parâmetros de entrada
3. Clicar em "Buscar"
4. Vai aparecer uma lista de empresas abaixo do mapa. Para cada empresa, retornar `nire`, `nome` e `endereco`.

Obs: não fazer paginação de resultados. Retornar os 100 primeiros resultados da primeira página.

![jucesp - pesquisa no mapa](https://user-images.githubusercontent.com/274526/114230048-062cd680-994f-11eb-9e89-b100c82a24ec.png)

### Qual é uma boa descrição desta consulta?

Localiza o Número de identificação do Registro de Empresas (NIRE) na Junta Comercial do Estado de São Paulo (JUCESP) a partir da pesquisa em mapa de empresas. A API retornará todos os resultados da primeira página de resultados.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral e fiscal de pessoas jurídicas, garantindo que dados informados estão atualizados e corretos.
- Pode ser usada para rastreamento de ativos.

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.

**Comment by leonardo-mdc** [comment]
Boa noite. Uso o site da jucesp para consultas das empresas nos arredores de um endereço específico e essa consulta via mapa seria perfeita pra mim.

Qual a chance de reativar?

**Comment by leonardo-mdc** [comment]
Enviei a resposta abaixo para o email informado mas retornou com erro de envio, segue abaixo:

```
Bom dia, em resposta à solicitação, eu faço alguns trabalhos de pesquisa para relatórios de avaliação de áreas para posterior investigação de passivo ambiental.

Nessa avaliação preliminar, preciso listar as informações de estabelecimentos nos arredores da área de interesse. Para tanto,, preciso gerar um mapa que será utilizado como referência pro relatório conforme a imagem anexa.

Preciso identificar determinados estabelecimentos em um raio de 200 e 500 metros, agregando informações da JUCESP e da CETESB,, e uma das dificuldades é que preciso listar nesse entorno as ruas e avenidas para só então pesquisar individualmente cada logradouro e depois ver se a numeração do imóvel está dentro ou fora do raio.

Tendo uma consulta que filtre as empresas mostrando no mapa, já me adianta em muito o trabalho de posicionamento. Se adicionalmente fosse possivel exportar arquivo com as coordenadas do que aparece na busca, seria o melhor dos mundos, mas mesmo que não seja possível, somente de ter a visualização da posição dos estabelecimentos já seria um avanço pro meu trabalho.
```
