### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT / Revogação de Primeiro Emplacamento

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#501]
### Nome da consulta:

SEFAZ / MT / Revogação de Primeiro Emplacamento

### URL da consulta:

https://www.sefaz.mt.gov.br/ipva/revogacao/PrimeiroEmplacamento

### Parâmetros de entrada necessários para fazer a consulta:

- chassi

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-primeiro-emplacamento/
