### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Guarulhos / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#502]
### Nome da consulta:

Prefeitura / SP / Guarulhos / Certidão Negativa de Débitos

### URL da consulta:

https://fazenda.guarulhos.sp.gov.br/ords/guarulho/f?p=628:98

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-sp-guarulhos-cnd/
