### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MS / Naviraí / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#503]
### Nome da consulta:

Prefeitura / MS / Naviraí / Certidão Negativa de Débitos

### URL da consulta:

https://navirai.govbr.cloud/certidao/emitircnd.php

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-pi-certidao-debitos/ e https://infosimples.com/consultas/sefaz-pi-visualizar-cert/

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-ms-navirai-cnd/
