### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SC / Blumenau / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#504]
### Nome da consulta:

Prefeitura / SC / Blumenau / Certidão Negativa de Débitos

### URL da consulta:

http://www.blumenau.sc.gov.br/cidadao/pages/siatu/cnd/EmissaoCND.aspx?Especial=N

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-sc-blumenau-cnd/
