### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Uberaba / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#505]
### Nome da consulta:

Prefeitura / MG / Uberaba / Certidão Negativa de Débitos

### URL da consulta:

https://iptu.uberaba.mg.gov.br/tributos/cnd/cnd.php

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-mg-uberaba-cnd/
