### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RJ / Duque de Caxias / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#506]
### Nome da consulta:

Prefeitura / RJ / Duque de Caxias / Certidão Negativa de Débitos

### URL da consulta:

https://www.tributosnet.com.br/duquedecaxias/portal/Modulos/Home.aspx#

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-rj-duque-de-caxias-cnd/
