### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT / Guia de IPVA

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#509]
### Nome da consulta:

SEFAZ / MT / Guia de IPVA

### URL da consulta:

https://www.sefaz.mt.gov.br/ipva/guiaipva/index.jsp

### Parâmetros de entrada necessários para fazer a consulta:

- chassi
- renavam

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-ipva/
