### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / AL / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#510]
### Nome da consulta:

SEFAZ / AL / NFC-e Completa

### URL da consulta:

https://nfce.sefaz.al.gov.br/consultaNFCe.htm

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-al-nfce/
