### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MS / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#512]
### Nome da consulta:

SEFAZ / MS / NFC-e Completa

### URL da consulta:

http://nfce.fazenda.mg.gov.br/portalnfce/sistema/consultaarg.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-ms-nfce/
