### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#513]
### Nome da consulta:

SEFAZ / MT / NFC-e Completa

### URL da consulta:

https://www.sefaz.mt.gov.br/nfce/consultanfce

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-nfce/
