### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PA / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#514]
### Nome da consulta:

SEFAZ / PA / NFC-e Completa

### URL da consulta:

https://app.sefa.pa.gov.br/consulta-nfce/#/consulta

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-pa-nfce/
