### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PB / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#515]
### Nome da consulta:

SEFAZ / PB / NFC-e Completa

### URL da consulta:

https://www.sefaz.pb.gov.br/servirtual/documentos-fiscais/nfc-e/consultar-nfc-e

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-pb-nfce/
