### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PR / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#516]
### Nome da consulta:

SEFAZ / PR / NFC-e Completa

### URL da consulta:

https://sped.fazenda.pr.gov.br/NFCe/webservices/sped/nfce/completa

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-pr-nfce/
