### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / RR / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#517]
### Nome da consulta:

SEFAZ / RR / NFC-e Completa

### URL da consulta:

https://portalapp.sefaz.rr.gov.br/nfce/consulta

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-rr-nfce/
