### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / SC / NFC-e Completa

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#518]
### Nome da consulta:

SEFAZ / SC / NFC-e Completa

### URL da consulta:

https://sat.sef.sc.gov.br/tax.net/Sat.Dfe.NFCe.Web/Consultas/ConsultaPublicaNFCe.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- nfce

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-sc-nfce/
