### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / CE / Fortaleza / Certidão Negativa de Débitos de IPTU

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#523]
### Nome da consulta:

Prefeitura / CE / Fortaleza / Certidão Negativa de Débitos de IPTU

### URL da consulta:

https://grpfor.sefin.fortaleza.ce.gov.br/grpfor/pagesPublic/certidoes/emitirCertidao.seam?tipoCertidao=5&cid=26245

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- inscricao

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/pref-ce-fortaleza-cnd/
