### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / PA / Belém / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#524]
### Nome da consulta:

Prefeitura / PA / Belém / Certidão Negativa de Débitos

### URL da consulta:

http://ww2.belem.pa.gov.br/cnde-e/cnde/solicitacao/solicitacert.cinb

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- sequencial
- inscricao

**Comment by rafaelivan** [comment]
O link do site não existe mais.
