### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT / Dívida Ativa 

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#529]
### Nome da consulta:

SEFAZ / MT / Dívida Ativa 

### URL da consulta:

https://www.sefaz.mt.gov.br/sgda/pages/negociacaoIpva/principal.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- cda
- chassi
- renavam

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pge-mt-divida-ativa/
