### ISSUE TITLE
[API de Automação de Consulta] IEPTB / Protestos (via CENPROT SP)

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#53]
### Nome da consulta:

IEPTB / Protestos (via CENPROT SP)

### URL da consulta:

https://www.protestosp.com.br/consulta-de-protesto

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf

### Qual é uma boa descrição desta consulta?

Consulta a existência e os dados de Protestos de pessoas físicas e jurídicas no Instituto de Estudos de Protesto de Titulos do Brasil (IEPTB) através do CENPROT SP. Apenas os resultados de SP têm retornos detalhados.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral e fiscal de pessoas físicas e jurídicas, garantindo que dados informados estão atualizados e corretos
- A existência de protestos contra pessoa física e jurídica pode ser utilizada em modelos de análise de crédito
- Pode ser usada para criação de dossiês ou em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente)

**Comment by rafaelnasser** [comment]
Está funcionando este crawler ainda?

**Comment by barbolo** [comment]
A API continua funcionando. Caso seja cliente da Infosimples, pode acompanhar o status da API em https://api.infosimples.com/consultas/status/ieptb/protestos.

**Comment by barbolo** [comment]
Esta API está funcionando: https://infosimples.com/consultas/ieptb-protestos/

A API desta issue está pendente de homologação e ainda não está em produção.

**Comment by adrianodennanni** [comment]
@barbolo podemos fechar esta issue?

**Comment by adrianodennanni** [comment]
Esta consulta foi disponibilizada em https://infosimples.com/consultas/ieptb-cenprotsp-protestos/
