### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SC / Joinville / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#530]
### Nome da consulta:

Prefeitura / SC / Joinville / Certidão Negativa de Débitos

### URL da consulta:

https://tmiweb.joinville.sc.gov.br/sefaz/jsp/cnd/index.jsp

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-sc-joinville-cnd/
