### ISSUE TITLE
[API de Automação de Consulta] Conselho Federal de Medicina Veterinária / Cadastro

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#531]
### Nome da consulta:

Conselho Federal de Medicina Veterinária / Cadastro

### URL da consulta:

https://www.cfmv.gov.br/busca-por-profissionais/servicos/2018/10/09/

### Parâmetros de entrada necessários para fazer a consulta:

- nome_completo
- uf
- inscricao

### Qual é uma boa descrição desta consulta?

Consulta cadastral de médicos veterinários no CFMV (Conselho Federal de Medicina Veterinária).

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/cfmv-cadastro/

**Comment by jappejappe** [comment]
Como posso fazer uma requisição pra essa API via script, sem navegador?

**Comment by adrianodennanni** [comment]
@jappejappe por favor, acesse https://infosimples.com
