### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJPR / Processos

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#532]
### Nome da consulta:

Tribunal / TJPR / Processos

### URL da consulta:

https://consulta.tjpr.jus.br/projudi_consulta/

### Parâmetros de entrada necessários para fazer a consulta:

- nome
- cpf
- cnpj
- numero_processo
- comarca
- juizo

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/tribunal-tjpr-processo/
