### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / Perolândia / Licitações

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#534]
### Nome da consulta:

Prefeitura / Perolândia / Licitações

### URL da consulta:

https://acessoainformacao.perolandia.go.gov.br/cidadao/informacao/licitacoes_cnt

### Parâmetros de entrada necessários para fazer a consulta:

- query
- orgao
- situacao
- modalidade

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/pref-go-perolandia-licitacoes/
