### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / GO / Catalão / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#535]
### Nome da consulta:

Prefeitura / GO / Catalão / Certidão Negativa de Débitos

### URL da consulta:

https://sig.catalao.go.gov.br/sig/app.html#/servicosonline/debito-contribuinte

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-go-catalao-cnd/
