### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / GO / Jataí / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#536]
### Nome da consulta:

Prefeitura / GO / Jataí / Certidão Negativa de Débitos

### URL da consulta:

http://gestaopublica.jatai.bsit-br.com.br/portal/person/search-certificate-debit.jsf

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-go-jatai-cnd/
