### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / GO / IPVA

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#537]
### Nome da consulta:

SEFAZ / GO / IPVA
### URL da consulta:

https://sistemas.sefaz.go.gov.br/snc/publico/ipva/form

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-go-ipva/
