### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RS / Farroupilha / NFS-e (Nota Fiscal Eletrônica de Serviços)

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#538]
### Nome da consulta:

Prefeitura / RS / Farroupilha / NFS-e (Nota Fiscal Eletrônica de Serviços)

### URL da consulta:

https://nfse.farroupilha.rs.gov.br/nfse/consultaExterna

### Parâmetros de entrada necessários para fazer a consulta:

- chave

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-rs-farroupilha-nfs/
