### ISSUE TITLE
[API de Automação de Consulta] DETRAN / RR / Gravame

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#54]
### Nome da consulta:

DETRAN / RR / Gravame

### URL da consulta:

https://www.detran.rr.gov.br/site/apps/veiculo/consultas/consulta_gravame.jsp

### Parâmetros de entrada necessários para fazer a consulta:

- chassi

### Qual é uma boa descrição desta consulta?

Consulta GRAVAME do veículo no Departamento Estadual de Trânsito (DETRAN) de Roraima (RR).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral e fiscal de veículos, garantindo que os dados informados estão atualizados e corretos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://api.infosimples.com/consultas/docs/detran/rr/gravame

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://infosimples.com/consultas/detran-rr-gravame/
