### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / Campinas / IPTU

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#541]
### Nome da consulta:

Prefeitura / SP / Campinas / IPTU

### URL da consulta:

https://iptu.campinas.sp.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- codigo_cartografico
- codigo_anterior

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/pref-sp-campinas-iptu/
