### ISSUE TITLE
[API de Automação de Consulta] DETRAN / MG / Pontuação CNH

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#543]
### Nome da consulta:

DETRAN / MG / Pontuação CNH

### URL da consulta:

https://transito.mg.gov.br/habilitacao/prontuario/consultar-pontuacao-cnh/

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- data_nascimento
- data_primeira_habilitacao

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/detran-mg-pontuacao-cnh/
