### ISSUE TITLE
[API de Automação de Consulta] ANTT / Produtos Perigosos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#544]
### Nome da consulta:

ANTT / Produtos Perigosos

### URL da consulta:

https://produtoperigoso.antt.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- tipo_certificado
- numero_certificado
- numero_equipamento
- placa
- renavam

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/antt-produtos-perigosos/
