### ISSUE TITLE
[API de Automação de Consulta] DNIT / Infrações (CNPJ)

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#545]
### Nome da consulta:

DNIT / Infrações (CNPJ)

### URL da consulta:

https://servicos.dnit.gov.br/multas/conta/login

### Parâmetros de entrada necessários para fazer a consulta:

- login_cnpj
- login_senha

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/dnit-infracoes/
