### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJSC / Requisição de Certidão

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#546]
### Nome da consulta:

Tribunal / TJSC / Requisição de Certidão
### URL da consulta:

https://certidoes.tjsc.jus.br/pedidoCertidao

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- tipo
- email
- municipio
- finalidade

### Passo a passo de como realizar manualmente a consulta:

1. PASSO_1
2. PASSO_2

### Qual é uma boa descrição desta consulta?

TEXTO_QUE_DESCREVE_BREVEMENTE_O_QUE_A_CONSULTA_FAZ.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- PROCESSO_1
- PROCESSO_2

### [OPCIONAL] Você gostaria de dizer algo mais que não perguntamos?

TEXTO_OPCIONAL

**Comment by rafaelivan** [comment]
As consulta foram disponibilizadas:
- https://infosimples.com/consultas/tribunal-tjsc-pedido-certidao/
- https://infosimples.com/consultas/tribunal-tjsc-obter-certidao/
