### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / RS / Porto Alegre / Comprovante de Inscrição do ISSQN

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#547]
### Nome da consulta:

Prefeitura / RS / Porto Alegre / Comprovante de Inscrição do ISSQN

### URL da consulta:

https://siat.procempa.com.br/siat/CpsEmitirComprovanteInscricao_Internet.do

### Parâmetros de entrada necessários para fazer a consulta:

- cnpj
- cpf

**Comment by adrianodennanni** [comment]
A API de consulta foi disponibilizada: https://infosimples.com/consultas/pref-rs-porto-alegre-issqn/
