### ISSUE TITLE
[API de Automação de Consulta] DETRAN / SP / Autenticidade de Certidão

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#548]
### Nome da consulta:

DETRAN / SP / Autenticidade de Certidão

### URL da consulta:

https://www.detran.sp.gov.br/wps/portal/portaldetran/cidadao/pesquisaCertidao

### Parâmetros de entrada necessários para fazer a consulta:

- codigo_certidao

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/detran-sp-autenticidade/
