### ISSUE TITLE
[API de Automação de Consulta] CNIS / Pré-inscrição

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#55]
### Nome da consulta:

CNIS / Pré-inscrição

### URL da consulta:

https://cnisnet.inss.gov.br/cnisinternet/faces/pages/inscricao/filiado/identificar.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- nome
- mae
- cpf
- data_nascimento

### Passo a passo de como realizar manualmente a consulta:

![consulta no CNIS](https://user-images.githubusercontent.com/274526/116300808-b3885280-a775-11eb-87fa-670746e6b67d.png)

### Qual é uma boa descrição desta consulta?

Consulta a inscrição (PIS/NIT/NIS) de uma pessoa física no Cadastro Nacional de Informações Sociais (CNIS).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Permite confirmar o número PIS/NIT/NIS de uma pessoa física brasileira

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by barbolo** [comment]
API publicada - https://infosimples.com/consultas/cnis-pre-inscricao/

**Comment by rapcardosojor** [comment]
preciso de uma API para baixar o cnis, consegue?

**Comment by barbolo** [comment]
Poderia explicar o que seria "baixar o cnis"?

**Comment by wagnerfp** [comment]
Consigo inserir esta api em meu crm, para consultar andamentos de processos de requerimento de benefício?
