### ISSUE TITLE
[API de Automação de Consulta] PJE / Consulta Pública Unificada

### ISSUE THREAD

**Issue by Daniel-Vaini** [infosimples/infosimples#551]
### Nome da consulta:

PJE / Consulta Pública Unificada

### URL da consulta:

https://consultaunificadapje.tse.jus.br/#/public/inicial/index

### Parâmetros de entrada necessários para fazer a consulta:

- numero_processo
- cpf
- cnpj

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/tse-pje/
