### ISSUE TITLE
[API de Automação de Consulta] FGTS / Guia de Arrecadação

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#554]
### Nome da consulta:

FGTS / Guia de Arrecadação

### URL da consulta:

https://fgtsdigital.sistema.gov.br/portal/login

### Parâmetros de entrada necessários para fazer a consulta:

- login_cpf
- login_senha
- pkcs12_cert
- pkcs12_pass
- periodo
- representado
- pagina

**Comment by rafaelivan** [comment]
As consultas foram disponibilizadas:
- https://infosimples.com/consultas/fgts-guia/
- https://infosimples.com/consultas/fgts-guia-rapida/
