### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJSP / Processos do 2º Grau

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#555]
### Nome da consulta:

Tribunal / TJSP / Processos do 2º Grau

### URL da consulta:

https://esaj.tjsp.jus.br/cposg/open.do

### Parâmetros de entrada necessários para fazer a consulta:

- processo
- parte
- cpf
- cnpj
- rg
- advogado
- oab
- carta_precatoria
- documento_delegacia
- pagina

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/tribunal-tjsp-segundo-grau/
