### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJSP / Colégio Recursal e Turma de Uniformização

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#556]
### Nome da consulta:

Tribunal / TJSP / Colégio Recursal e Turma de Uniformização

### URL da consulta:

https://esaj.tjsp.jus.br/cposgcr/open.do

### Parâmetros de entrada necessários para fazer a consulta:

- processo
- parte
- cpf
- cnpj
- rg
- advogado
- oab
- carta_precatoria
- documento_delegacia
- pagina

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/tribunal-tjsp-colegio-recursal/
