### ISSUE TITLE
[API de Automação de Consulta] INCRA / SIGEF / Requerimentos

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#558]
### Nome da consulta:

INCRA / SIGEF / Requerimentos

### URL da consulta:

https://sigef.incra.gov.br/consultar/requerimentos

### Parâmetros de entrada necessários para fazer a consulta:

- protocolo
- cpf
- cnpj
- nome_razao_social
- codigo_parcela
- cns
- matricula
- processo
- credenciado
- vertice
- scnr

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/incra-sigef-requerimentos/
