### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TRF2 / Processo (eproc)

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#559]
### Nome da consulta:

Tribunal / TRF2 / Processo (eproc)

### URL da consulta:

https://eproc.trf2.jus.br/eproc/externo_controlador.php?acao=processo_consulta_publica&acao_origem=&acao_retorno=processo_consulta_publica

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- numero_processo
- nome_parte
- oab

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/tribunal-trf2-processo-eproc/
