### ISSUE TITLE
[API de Automação de Consulta] Conselho Federal de Psicologia / Cadastro

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#560]
### Nome da consulta:

Conselho Federal de Psicologia / Cadastro

### URL da consulta:

https://cadastro.cfp.org.br/

### Parâmetros de entrada necessários para fazer a consulta:

- nome
- uf
- registro
- cpf

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/cfp-cadastro/
