### ISSUE TITLE
[API de Automação de Consulta] ECAC / DCTF-WEB

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#561]
### Nome da consulta:

ECAC / DCTFWEB

### URL da consulta:

https://cav.receita.fazenda.gov.br/ecac/Aplicacao.aspx?id=10015&origem=pesquisa

### Parâmetros de entrada necessários para fazer a consulta:

- pkcs12_cert
- pkcs12_pass
- periodo
- categoria

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/ecac-dctf-web/

**Comment by caiolandgraf** [comment]
existe alguma API para fazer o envio? Aparentemente esta é apenas para consulta

**Comment by RCrislane** [comment]
bom dia, tem disponibilização do código??

**Comment by barbolo** [comment]
Não disponibilizamos uma API para envio. Mais informações sobre essa API podem ser ecnontradas no link 
https://infosimples.com/consultas/ecac-dctf-web/.
