### ISSUE TITLE
[API de Automação de Consulta] Contas / Neoenergia Elektro / Download

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#562]
### Nome da consulta:

Contas / Neoenergia Elektro / Download

### URL da consulta:

https://agencia.neoenergiaelektro.com.br/login.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- senha
- uc
- mes_ano

**Comment by rafaelivan** [comment]
As APIs foram disponibilizadas:
- https://infosimples.com/consultas/contas-neoenergia-download/
- https://infosimples.com/consultas/contas-neoenergia-download-ocr/
