### ISSUE TITLE
[API de Automação de Consulta] PRF / Débitos

### ISSUE THREAD

**Issue by OtavioAugustoBruzadin** [infosimples/infosimples#564]
### Nome da consulta:

PRF / Débitos

### URL da consulta:

https://pesquisa-auto.prf.gov.br/#/pesquisa/consultar-debitos

### Parâmetros de entrada necessários para fazer a consulta:

- Placa
- Renavam

### Qual é uma boa descrição desta consulta?

Consulta débitos de um veículo através da placa e do Renavam.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/prf-debitos/
