### ISSUE TITLE
[API de Automação de Consulta] Contas / SAESA / Download

### ISSUE THREAD

**Issue by pedroegydio01** [infosimples/infosimples#565]
### Nome da consulta:

Contas / SAESA / Download

### URL da consulta:

http://www.daescs.sp.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- codigo_ligacao

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/contas-saesa-download/
