### ISSUE TITLE
[API de Automação de Consulta] Portal da Transparência / Servidor Público

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#57]
### Nome da consulta:

Portal da Transparência / Servidor Público

### URL da consulta:

http://www.portaltransparencia.gov.br/servidores/consulta?ordenarPor=nome&direcao=asc

### Parâmetros de entrada necessários para fazer a consulta:

- cpf

### Passo a passo de como realizar manualmente a consulta:

![consulta servidor público](https://user-images.githubusercontent.com/274526/116301811-d5360980-a776-11eb-98ae-6370ef794504.png)

### Qual é uma boa descrição desta consulta?

Consulta detalhamento de um servidor público no Portal da Transparência, incluindo dados do vínculo, ficha de remuneração e viagens a serviço.

**Comment by adrianodennanni** [comment]
Disponível em https://infosimples.com/consultas/portal-transparencia-servidor/
