### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MG / Janaúba / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#574]
### Nome da consulta:

Prefeitura / MG / Janaúba / Certidão Negativa de Débitos

### URL da consulta:

https://janauba.sintesetecnologia.com.br/portalDeServicos/publica/emissaoCNDContribuinte.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Passo a passo de como realizar manualmente a consulta:

1. PASSO_1
2. PASSO_2

### Qual é uma boa descrição desta consulta?

TEXTO_QUE_DESCREVE_BREVEMENTE_O_QUE_A_CONSULTA_FAZ.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- PROCESSO_1
- PROCESSO_2

### [OPCIONAL] Você gostaria de dizer algo mais que não perguntamos?

TEXTO_OPCIONAL

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-mg-janauba-cnd/
