### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJSP / Selo Digital

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#575]
### Nome da consulta:

Tribunal / TJSP / Selo Digital

### URL da consulta:

https://selodigital.tjsp.jus.br/consulta

### Parâmetros de entrada necessários para fazer a consulta:

- selo

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/tribunal-tjsp-selo-digital/
