### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MS / Dourados / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by guilhermesousainacio** [infosimples/infosimples#579]
### Nome da consulta:
Prefeitura / MS / Dourados / Certidão Negativa de Débitos

### URL da consulta:

https://e-gov.betha.com.br/cdweb/03114-445/main.faces

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Passo a passo de como realizar manualmente a consulta:

1. Selecione o Estado desejado = mS - Mato Grosso do Sul. 
2. No Campo Entidade selecione o Município de Dourado. 
3. Clique em Acessar.
4. Permitir Pop-ups
5. Será redirecionado para a tela de Boas-vindas.
6. No menu lateral acesse “Emitir” e em seguida clique em “Certidão negativa de contribuinte”.
7. Abrirá a tela onde será incluído o CPF ou CNPJ da empresa a ser consultada. Selecionar a opção conforme o documento que será consultado. CNPJ ou CPF. 
8. Adicionar o CNPJ e clicar em “Continuar”.
9. Abrirá uma nova tela onde deve preencher com os dados para busca. Comprovação junto á: cnd. Finalidade: débitos.
10. Após clique no ícone da impressora. O site irá processar os dados e gerar o documento que deve ser disponibilizado em pdf para o cliente.### Qual é uma boa descrição desta consulta?

Emite Certidão Negativa/Positiva de Débitos municipais

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- PROCESSO_1
- PROCESSO_2

### [OPCIONAL] Você gostaria de dizer algo mais que não perguntamos?

TEXTO_OPCIONAL

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/pref-ms-dourados-cnd/
