### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MT / Rondonópolis / Certidão Negativa de Débitos

### ISSUE THREAD

**Issue by guilhermesousainacio** [infosimples/infosimples#580]
### Nome da consulta:

Prefeitura / MT / Rondonópolis / Certidão Negativa de Débitos

### URL da consulta:
https://blue.rondonopolis.mt.gov.br/portal/rondonopolis/#/certidao

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Passo a passo de como realizar manualmente a consulta:

1. Após colocar os dados e clicar em imprimir abrirá uma nova modal,  onde o usuário deve selecionar se quer uma nova CND, ou uma reimpressão. , selecione para imprimir uma nova.
2. Se a empresa se encontrar com tudo em dia será emitida a Certidão Negativa. 
3.   Caso contrario será exibida uma mensagem avisando. Não é emita a CND Positiva para a empresa. ”Não é permitido gerar certidão negativa de débitos quando o contribuinte/econômico/imobiliário possuir débitos.”

### Qual é uma boa descrição desta consulta?

Emite Certidão Negativa de Débitos.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- PROCESSO_1
- PROCESSO_2

### [OPCIONAL] Você gostaria de dizer algo mais que não perguntamos?

TEXTO_OPCIONAL

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-mt-rondonopolis-cnd/
