### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / MS / Calculadora de Fretes

### ISSUE THREAD

**Issue by OtavioAugustoBruzadin** [infosimples/infosimples#587]
### Nome da consulta:

Prefeitura / MS / Calculadora de Fretes

### URL da consulta:

https://servicos.efazenda.ms.gov.br/calculafrete

### Parâmetros de entrada necessários para fazer a consulta:

- Peso (Em Toneladas)
- Distancia
- Data da prestação do serviço
- 
### Qual é uma boa descrição desta consulta?

Calcular o valor de frete com base na Pauta de frete definida pelo estado do Mato Grosso do Sul

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/pref-ms-calculadora-frete/
