### ISSUE TITLE
[API de Automação de Consulta] Antecedentes Criminais / MS

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#61]
### Nome da consulta:

Antecedentes Criminais / MS

### URL da consulta:

http://antecedentes.sejusp.ms.gov.br/pages/MasterPages/IUPrincipal.aspx#

### Parâmetros de entrada necessários para fazer a consulta:

- nome
- mae
- pai
- data_nascimento
- sexo
- rg
- rg_digito
- orgao_emissor
- uf

### Passo a passo de como realizar manualmente a consulta:

![consulta antecedentes criminais MS](https://user-images.githubusercontent.com/274526/116317641-fd7b3380-a789-11eb-9ef8-ca3e8bcd14f0.png)

### Qual é uma boa descrição desta consulta?

Emite Atestado de Antecedentes no portal da Polícia Civil do Rio Grande do Sul. IMPORTANTE - O não fornecimento do Atestado de Antecedentes Criminais não implica a existência de pendências jurídico-criminais.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em conjunto com outras certidões para Due Diligence (Auditoria Prévia) de pessoas e empresas.
- Pode ser usada para criação de dossiês ou em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente)
- Pode ser usada para confirmar dados cadastrais de uma Carteira de Identidade (RG) da UF de MS.

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
Alternativamente, você pode usar a consulta [API de Antecedentes Criminais / Polícia Federal](https://infosimples.com/consultas/antecedentes-criminais-dpf/)
