### ISSUE TITLE
[API de Automação de Consulta] DETRAN / MT / Veículo

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#62]
### Nome da consulta:

DETRAN / MT / Veículo

### URL da consulta:

https://www.detran.mt.gov.br/

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

### Qual é uma boa descrição desta consulta?

Consulta cadastro do veículo no Departamento Estadual de Trânsito (DETRAN) do Mato Grosso (MT).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral e fiscal de veículos, garantindo que os dados do veículo estão atualizados e corretos.
- Pode ser usado por locadoras de veículos para monitorar frotas de veículos.

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://api.infosimples.com/consultas/docs/detran/mt/veiculo

**Comment by adrianodennanni** [comment]
Consulta disponibilizada em https://infosimples.com/consultas/detran-mt-veiculo/
