### ISSUE TITLE
[API de Automação de Consulta] Prefeitura / SP / São Paulo / AIT

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#63]
### Nome da consulta:

Prefeitura / SP / São Paulo / AIT

### URL da consulta:

https://meuveiculo.prefeitura.sp.gov.br/forms/frmPesquisarRenavam.aspx

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

### Qual é uma boa descrição desta consulta?

Consulta a existência de Autos de Infração de Trânsito (AIT) de um veículo do Município de São Paulo.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para fiscalizar e monitorar a existência de autuações vinculadas ao veículo e verificar detalhes da localização, data e hora, situação entre outros.
- Pode ser usada para gerenciar o pagamento de débitos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
A API foi disponibilizada - https://infosimples.com/consultas/pref-sp-sao-paulo-ait/
