### ISSUE TITLE
[API de Automação de Consulta] DETRAN / GO / Completa

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#64]
### Nome da consulta:

DETRAN / GO / Completa

### URL da consulta:

https://www.detran.go.gov.br/psw/#/pages/conteudo/consulta-veiculo

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam
- chassi

### Qual é uma boa descrição desta consulta?

Consulta cadastro do veículo no Departamento Estadual de Trânsito (DETRAN) de Goiás (GO).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão cadastral e fiscal de veículos, garantindo que os dados do veículo estão atualizados e corretos.

**Comment by rafaelivan** [comment]
A API foi desenvolvido e publicada: https://infosimples.com/consultas/detran-go-completa/
