### ISSUE TITLE
[API de Automação de Consulta] Antecedentes Criminais / ES

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#67]
### Nome da consulta:

Antecedentes Criminais / ES

### URL da consulta:

http://ssp.sesp.es.gov.br/rgantecedentes/xhtml/pesquisaantecedentes.jsf

### Passo a passo de como realizar manualmente a consulta:

![consulta antecedentes criminais ES](https://user-images.githubusercontent.com/274526/118640746-b8a65380-b7af-11eb-8e29-0986dcfd0350.png)

### Qual é uma boa descrição desta consulta?

Emite Atestado de Antecedentes no portal da Polícia Civil do Rio Grande do Sul. IMPORTANTE - O não fornecimento do Atestado de Antecedentes Criminais não implica a existência de pendências jurídico-criminais.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em conjunto com outras certidões para Due Diligence (Auditoria Prévia) de pessoas e empresas.
- Pode ser usada para criação de dossiês ou em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente)
- Pode ser usada para confirmar dados cadastrais de uma Carteira de Identidade (RG) da UF de ES.

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
Alternativamente, você pode usar a consulta [API de Antecedentes Criminais / Polícia Federal](https://infosimples.com/consultas/antecedentes-criminais-dpf/)
