### ISSUE TITLE
[API de Automação de Consulta] ESALQ / CEPEA

### ISSUE THREAD

**Issue by barbolo** [infosimples/infosimples#72]
### Nome da consulta:

ESALQ / CEPEA

### URL da consulta:

https://cepea.esalq.usp.br/br

### Qual é uma boa descrição desta consulta?

Consulta preços de produtos agropecuários monitorados pelo CEPEA (Centro de Estudos Avançados em Economia Aplicada) da ESALQ (Escola Superior de Agricultura Luiz de Queiroz).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Monitorar preços de commodities agrícolas.
- Avaliar recebíveis agropecuários.

**Comment by barbolo** [comment]
API disponível em https://infosimples.com/consultas/esalq-cepea/

**Comment by Matheuspombopedroso** [comment]
Como fazer as consultas? Existe alguma documentação para essa API?

**Comment by barbolo** [comment]
Entre em contato com suporte@infosimples.com.br.
