### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TRT2 / Certidão de Ações Trabalhistas

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#75]
### Nome da consulta:

Tribunal / TRT2 / Certidão de Ações Trabalhistas

### URL da consulta:

https://aplicacoes10.trt2.jus.br/certidao_trabalhista_eletronica/public/index.php/index/solicitacao

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Emite Certidão Online de Ações Trabalhistas no TRT2 (Tribunal Regional do Trabalho da 2ª Região).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
- Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta disponível em https://infosimples.com/consultas/tribunal-trt2-ceat/
