### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / AL / IPVA (ano atual)

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#76]
### Nome da consulta:

SEFAZ / AL / IPVA (ano atual)

### URL da consulta:

http://apl03.sefaz.al.gov.br/ipvaonline/

### Parâmetros de entrada necessários para fazer a consulta:

- renavam
- placa

### Qual é uma boa descrição desta consulta?

Pesquisa dados de Imposto sobre Propriedades de Veículos Automotores (IPVA) do ano atual, através do número de RENAVAM e placa.

### Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para prevenir fraudes, confirmando se o veículo informado possui débitos de IPVA.
- Pode ser usada em gestão cadastral e fiscal do veículo, garantindo que os dados informados estão atualizados e corretos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
A consulta está disponível: https://infosimples.com/consultas/sefaz-al-ipva/
