### ISSUE TITLE
[API de Automação de Consulta] DETRAN / CE / Certidão Negativa de Débitos (por placa)

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#77]
### Nome da consulta:

DETRAN / CE / Certidão Negativa de Débitos (por placa)

### URL da consulta:

https://sistemas.detran.ce.gov.br/central/

### Parâmetros de entrada necessários para fazer a consulta:

- placa

### Qual é uma boa descrição desta consulta?

Emite Certidão Negativa de Débitos no DETRAN CE através da placa de um veículo.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usado em gestão fiscal, verificando se existe pendências junto a órgãos públicos.
- Pode ser usada para prevenir fraudes, confirmando se o veículo informado possui débitos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/detran-ce-certidao-debitos/
