### ISSUE TITLE
[API de Automação de Consulta] DETRAN / MA / Restrições

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#78]
### Nome da consulta:

DETRAN / MA / Restrições

### URL da consulta:

http://www.detran.ma.gov.br/Restricoes/

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam

### Qual é uma boa descrição desta consulta?

Consulta a existência de restrições no DETRAN MA através da placa e do RENAVAM de um veículo.

### Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para prevenir fraudes, confirmando se o veículo informado possui restrições.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
A consulta está disponível: https://infosimples.com/consultas/detran-ma-restricoes/
