### ISSUE TITLE
[API de Automação de Consulta] Tribunal / TJAC / Processo

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#8]
### Nome da consulta:

Tribunal / TJAC / Processo

### URL da consulta:

https://esaj.tjac.jus.br/cposg5/open.do

### Parâmetros de entrada necessários para fazer a consulta:

* processo
* parte
* rg
* cpf
* advogado
* classe
* oab

### Qual é uma boa descrição desta consulta?

Consulta a situação de processos no TJAC (Tribunal de Justiça do Acre).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

* Pode ser usada para verificar se existem ações em tramitação para uma pessoa física ou pessoa jurídica.
* Pode ser usada em processos de KYC (Know Your Customer, ou, Conheça Seu Cliente).

**Comment by adrianodennanni** [comment]
Consulta descartada por falta de interesse e parâmetros necessários para desenvolvimento. Se você tiver interesse nela, por favor entre em contato.
