### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / MT / IPVA

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#80]
### Nome da consulta:

SEFAZ / MT / IPVA

### URL da consulta:

https://www.sefaz.mt.gov.br/ipva/emissaoguia/emitir

### Parâmetros de entrada necessários para fazer a consulta:

- renavam
- chassi

### Qual é uma boa descrição desta consulta?

Pesquisa dados de Imposto sobre Propriedades de Veículos Automotores (IPVA).

### Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para prevenir fraudes, confirmando se o veículo informado possui débitos de IPVA.
- Pode ser usada em gestão cadastral e fiscal do veículo, garantindo que os dados informados estão atualizados e corretos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
A API foi disponibilizada: https://infosimples.com/consultas/sefaz-mt-ipva/
