### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / PI / IPVA

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#82]
### Nome da consulta:

SEFAZ / PI / IPVA

### URL da consulta:

http://webas.sefaz.pi.gov.br/darweb/faces/views/ipva/ipva.xhtml

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj
- renavam
- chassi

### Qual é uma boa descrição desta consulta?

Pesquisa dados de Imposto sobre Propriedades de Veículos Automotores (IPVA).

### Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para prevenir fraudes, confirmando se o veículo informado possui débitos de IPVA.
- Pode ser usada em gestão cadastral e fiscal do veículo, garantindo que os dados informados estão atualizados e corretos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
Consulta disponibilizada: https://infosimples.com/consultas/sefaz-pi-ipva/
