### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / RO / IPVA

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#84]
### Nome da consulta:

SEFAZ / RO / IPVA

### URL da consulta:

https://portalcontribuinte.sefin.ro.gov.br/Publico/ConsultaRenavam.jsp

### Parâmetros de entrada necessários para fazer a consulta:

- renavam

### Qual é uma boa descrição desta consulta?

Pesquisa dados de Imposto sobre Propriedades de Veículos Automotores (IPVA).

### Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para prevenir fraudes, confirmando se o veículo informado possui débitos de IPVA.
- Pode ser usada em gestão cadastral e fiscal do veículo, garantindo que os dados informados estão atualizados e corretos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/sefaz-ro-ipva/
