### ISSUE TITLE
[API de Automação de Consulta] DETRAN / MG / Publicação de Dano

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#85]
### Nome da consulta:

DETRAN / MG / Publicação de Dano

### URL da consulta:

https://www.detran.mg.gov.br/veiculos/acidentes/edital-de-publicacao-de-dano-de-media-e-grande-monta

### Parâmetros de entrada necessários para fazer a consulta:

- placa

### Qual é uma boa descrição desta consulta?

Consulta se o veículo possui publicação de dano de média ou grande monta no DETRAN MG.

### Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para verificar se o veículo sinistrado foi afetado nos seus componentes mecânicos e estruturais, envolvendo a substituição de equipamentos de segurança especificados pelo fabricante.
- Pode ser usada para verificar a perda total de veículo sinistrado.
- Pode ser usada em gestão cadastral e fiscal do veículo, garantindo que os dados informados estão atualizados e corretos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/detran-mg-publicacao-dano/
