### ISSUE TITLE
[API de Automação de Consulta] DETRAN / RJ / GRT (Guia de Regularização de Taxas)

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#86]
### Nome da consulta:

DETRAN / RJ / GRT (Guia de Regularização de Taxas)

### URL da consulta:

https://www.ib7.bradesco.com.br/ibpfdetranrj/DebitoVeiculoRJGRTLoaderAction.do

### Parâmetros de entrada necessários para fazer a consulta:

- renavam

### Qual é uma boa descrição desta consulta?

Consulta e emite GRT (Guia de Regularização de Taxas) de um veículo no DETRAN do Rio de Janeiro (RJ), através do RENAVAM.

### Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para gestão cadastral e fiscal de contas a pagar, assegurando que os boletos de taxas veiculares sejam pagas dentro do prazo descrito e que seus dados estejam corretos.
- Pode ser usado por locadoras de veículos para monitorar frotas de veículos.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by rafaelivan** [comment]
A consulta foi disponibilizada: https://infosimples.com/consultas/detran-rj-grt/
