### ISSUE TITLE
[API de Automação de Consulta] DENATRAN / Recall

### ISSUE THREAD

**Issue by adrianodennanni** [infosimples/infosimples#87]
### Nome da consulta:

DENATRAN / Recall

### URL da consulta:

https://portalservicos.denatran.serpro.gov.br/#/recall

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- chassi

### Qual é uma boa descrição desta consulta?

Informa se um recall foi disponibilizado para um veículo.

**Comment by rafaelivan** [comment]
A consulta foi desenvolvida e está disponível: https://infosimples.com/consultas/denatran-recall/
