### ISSUE TITLE
[API de Automação de Consulta] Receita Federal / PER/DCOMP

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#88]
### Nome da consulta:

Receita Federal / PER/DCOMP

### URL da consulta:

https://play.google.com/store/apps/details?id=br.gov.fazenda.receita.perdcomp&hl=pt_BR&gl=US

### Parâmetros de entrada necessários para fazer a consulta:

- cpf
- cnpj

### Qual é uma boa descrição desta consulta?

Consulta a lista de PER/DCOMP (Pedido Eletrônico de Restituição, Ressarcimento ou Reembolso e Declaração de Compensação) no aplicativo mobile da Receita Federal.

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada em gestão fiscal.
- Pode ser usada para monitorar PERDCOMP.

**Comment by LucasAmaral42** [comment]
A API já foi desenvolvida. Está pendente de revisão para ir pro ar.

**Comment by barbolo** [comment]
Foi disponibilizada em https://infosimples.com/consultas/receita-federal-perdcomp/
