### ISSUE TITLE
[API de Automação de Consulta] Portal da Transparência / Convênios e Acordos

### ISSUE THREAD

**Issue by LucasAmaral42** [infosimples/infosimples#89]
### Nome da consulta:

Portal da Transparência / Convênios e Acordos

### URL da consulta:

https://portaldatransparencia.cgu.gov.br/convenios/consulta?ordenarPor=orgao&direcao=desc

### Parâmetros de entrada necessários para fazer a consulta:

- numero

### Qual é uma boa descrição desta consulta?

Consulta detalhes de Convênios e outros Acordos no Portal da Transparência.

**Comment by barbolo** [comment]
API publicada em https://infosimples.com/consultas/portal-transparencia-convenios/
