### ISSUE TITLE
[API de Automação de Consulta] SEFAZ / TO / IPVA

### ISSUE THREAD

**Issue by rafaelivan** [infosimples/infosimples#99]
### Nome da consulta:

SEFAZ / TO / IPVA

### URL da consulta:

http://www.sefaz2.to.gov.br/ipva/dare.php

### Parâmetros de entrada necessários para fazer a consulta:

- placa
- renavam
- cpf

### Qual é uma boa descrição desta consulta?

Pesquisa dados de Imposto sobre Propriedades de Veículos Automotores (IPVA).

### [OPCIONAL] Você gostaria de usar esta API para automatizar que tipo de processo da sua empresa?

- Pode ser usada para prevenir fraudes, confirmando se o veículo informado possui débitos de IPVA.
- Pode ser usada em gestão cadastral e fiscal do veículo, garantindo que os dados informados estão atualizados e corretos.

**Comment by adrianodennanni** [comment]
Disponível em: https://infosimples.com/consultas/sefaz-to-ipva/
